/**
 * seed-badges.ts
 *
 * Upserts hardcoded achievement badges into the database.
 * Run with:  npx tsx prisma/seed-badges.ts
 *
 * All fields (icon, name, description, etc.) are easily modifiable here.
 * The `autoConditionKey` links each badge to the auto-award logic in
 * backend/src/utils/badgeAwards.ts — add matching keys there when adding new badges.
 */
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// ─── Badge definitions ────────────────────────────────────────────────────────

const BADGES = [
  // ── Core membership / rankings ─────────────────────────────────────────────
  {
    key: 'MEMBER',
    name: 'Membre AuraTracker',
    description: 'Membre officiel de la communauté AuraTracker.',
    howToObtain: 'Avoir un compte approuvé sur AuraTracker.',
    icon: '🔰',
    iconColor: '#f0fdfa',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#0f766e', to: '#14b8a6', direction: 'to bottom right' }),
    backgroundColor: '#0f766e',
    borderColor: '#2dd4bf',
    category: 'special',
    rarity: 'uncommon',
    isAutomatic: true,
    autoConditionKey: 'MEMBER',
  },
  {
    key: 'TOP_1_AURA',
    name: '#1 Aura',
    description: 'Le joueur avec le plus d\'aura sur toute la plateforme.',
    howToObtain: 'Avoir le plus d\'aura parmi tous les joueurs.',
    icon: '👑',
    iconColor: '#fff7ed',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#b45309', to: '#f59e0b', direction: 'to bottom right' }),
    backgroundColor: '#b45309',
    borderColor: '#f59e0b',
    category: 'leaderboard',
    rarity: 'legendary',
    isAutomatic: true,
    autoConditionKey: 'TOP_1_AURA',
  },
  {
    key: 'TOP_3_AURA',
    name: 'Top 3 Aura',
    description: 'Parmi les 3 joueurs avec le plus d\'aura.',
    howToObtain: 'Être dans le top 3 du classement aura.',
    icon: '✨',
    iconColor: '#faf5ff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#6d28d9', to: '#a855f7', direction: 'to bottom right' }),
    backgroundColor: '#6d28d9',
    borderColor: '#a855f7',
    category: 'leaderboard',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'TOP_3_AURA',
  },
  {
    key: 'TOP_5_AURA',
    name: 'Top 5 Aura',
    description: 'Parmi les 5 joueurs avec le plus d\'aura.',
    howToObtain: 'Être dans le top 5 du classement aura.',
    icon: '⚡',
    iconColor: '#eff6ff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#1d4ed8', to: '#3b82f6', direction: 'to bottom right' }),
    backgroundColor: '#1d4ed8',
    borderColor: '#60a5fa',
    category: 'leaderboard',
    rarity: 'rare',
    isAutomatic: true,
    autoConditionKey: 'TOP_5_AURA',
  },
  {
    key: 'TOP_10_AURA',
    name: 'Top 10 Aura',
    description: 'Parmi les 10 joueurs avec le plus d\'aura.',
    howToObtain: 'Être dans le top 10 du classement aura.',
    icon: '🌟',
    iconColor: '#f0fdf4',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#15803d', to: '#22c55e', direction: 'to bottom right' }),
    backgroundColor: '#15803d',
    borderColor: '#4ade80',
    category: 'leaderboard',
    rarity: 'uncommon',
    isAutomatic: true,
    autoConditionKey: 'TOP_10_AURA',
  },
  {
    key: 'TOP_1_MONEY',
    name: '#1 Argent',
    description: 'Le joueur le plus riche de la plateforme.',
    howToObtain: 'Avoir le plus d\'argent parmi tous les joueurs.',
    icon: '💎',
    iconColor: '#fff7ed',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#b45309', to: '#f59e0b', direction: 'to bottom right' }),
    backgroundColor: '#b45309',
    borderColor: '#f59e0b',
    category: 'leaderboard',
    rarity: 'legendary',
    isAutomatic: true,
    autoConditionKey: 'TOP_1_MONEY',
  },
  {
    key: 'TOP_3_MONEY',
    name: 'Top 3 Argent',
    description: 'Parmi les 3 joueurs les plus riches.',
    howToObtain: 'Être dans le top 3 du classement argent.',
    icon: '💰',
    iconColor: '#faf5ff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#6d28d9', to: '#a855f7', direction: 'to bottom right' }),
    backgroundColor: '#6d28d9',
    borderColor: '#a855f7',
    category: 'leaderboard',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'TOP_3_MONEY',
  },
  {
    key: 'TOP_5_MONEY',
    name: 'Top 5 Argent',
    description: 'Parmi les 5 joueurs les plus riches.',
    howToObtain: 'Être dans le top 5 du classement argent.',
    icon: '💵',
    iconColor: '#eff6ff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#1d4ed8', to: '#3b82f6', direction: 'to bottom right' }),
    backgroundColor: '#1d4ed8',
    borderColor: '#60a5fa',
    category: 'leaderboard',
    rarity: 'rare',
    isAutomatic: true,
    autoConditionKey: 'TOP_5_MONEY',
  },
  {
    key: 'TOP_10_MONEY',
    name: 'Top 10 Argent',
    description: 'Parmi les 10 joueurs les plus riches.',
    howToObtain: 'Être dans le top 10 du classement argent.',
    icon: '🪙',
    iconColor: '#f0fdf4',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#15803d', to: '#22c55e', direction: 'to bottom right' }),
    backgroundColor: '#15803d',
    borderColor: '#4ade80',
    category: 'leaderboard',
    rarity: 'uncommon',
    isAutomatic: true,
    autoConditionKey: 'TOP_10_MONEY',
  },

  // ── Effort / Grind ──────────────────────────────────────────────────────────
  {
    key: 'TRYHARDEUR',
    name: 'Tryhardeur',
    description: 'A joué plus de 100 parties au total, tous jeux confondus.',
    howToObtain: 'Joue 100 parties sur n\'importe quel jeu de la plateforme.',
    icon: '💪',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#f97316', to: '#dc2626', direction: 'to bottom right' }),
    backgroundColor: '#f97316',
    borderColor: '#f97316',
    category: 'achievement',
    rarity: 'uncommon',
    isAutomatic: true,
    autoConditionKey: 'TRYHARDEUR',
  },
  {
    key: 'GRIND_200',
    name: 'No Life',
    description: 'A joué plus de 200 parties au total. Il a vraiment rien d\'autre à faire.',
    howToObtain: 'Joue 200 parties sur n\'importe quel jeu.',
    icon: '🔥',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#991b1b', to: '#7c3aed', direction: 'to bottom right' }),
    backgroundColor: '#991b1b',
    borderColor: '#ef4444',
    category: 'achievement',
    rarity: 'rare',
    isAutomatic: true,
    autoConditionKey: 'GRIND_200',
  },

  // ── 2048 ─────────────────────────────────────────────────────────────────────
  {
    key: 'GAME_2048_TILE_2048',
    name: '2048',
    description: 'A accompli la tuile 2048 dans le jeu du même nom.',
    howToObtain: 'Atteins la tuile 2048 dans le jeu 2048.',
    icon: '🎯',
    iconColor: '#fbbf24',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#1d4ed8', to: '#7c3aed', direction: 'to bottom right' }),
    backgroundColor: '#1d4ed8',
    borderColor: '#60a5fa',
    category: 'achievement',
    rarity: 'rare',
    isAutomatic: true,
    autoConditionKey: 'GAME_2048_TILE_2048',
  },
  {
    key: 'GAME_2048_TILE_4096',
    name: '4096',
    description: 'A atteint la légendaire tuile 4096. Un vrai génie des chiffres.',
    howToObtain: 'Atteins la tuile 4096 dans le jeu 2048.',
    icon: '🧠',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#4c1d95', to: '#0f172a', direction: 'to bottom right' }),
    backgroundColor: '#4c1d95',
    borderColor: '#c084fc',
    category: 'achievement',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'GAME_2048_TILE_4096',
  },

  // ── Sudoku ───────────────────────────────────────────────────────────────────
  {
    key: 'SUDOKU_COMPLETED',
    name: 'Sudokiste',
    description: 'A complété une grille de sudoku. La logique ne lui fait pas peur.',
    howToObtain: 'Termine une grille de sudoku.',
    icon: '🧩',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#065f46', to: '#0f766e', direction: 'to bottom right' }),
    backgroundColor: '#065f46',
    borderColor: '#34d399',
    category: 'achievement',
    rarity: 'uncommon',
    isAutomatic: true,
    autoConditionKey: 'SUDOKU_COMPLETED',
  },
  {
    key: 'SUDOKU_EASY',
    name: 'Sudoku Facile',
    description: 'A complété une grille de sudoku en mode Facile.',
    howToObtain: 'Termine une grille de sudoku en difficulté Facile.',
    icon: '🧩',
    iconColor: '#f0fdf4',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#166534', to: '#22c55e', direction: 'to bottom right' }),
    backgroundColor: '#166534',
    borderColor: '#86efac',
    category: 'achievement',
    rarity: 'common',
    isAutomatic: true,
    autoConditionKey: 'SUDOKU_EASY',
  },
  {
    key: 'SUDOKU_MEDIUM',
    name: 'Sudoku Intermédiaire',
    description: 'A complété une grille de sudoku en mode Intermédiaire.',
    howToObtain: 'Termine une grille de sudoku en difficulté Intermédiaire.',
    icon: '🧩',
    iconColor: '#f0f9ff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#0369a1', to: '#0ea5e9', direction: 'to bottom right' }),
    backgroundColor: '#0369a1',
    borderColor: '#7dd3fc',
    category: 'achievement',
    rarity: 'uncommon',
    isAutomatic: true,
    autoConditionKey: 'SUDOKU_MEDIUM',
  },
  {
    key: 'SUDOKU_HARD',
    name: 'Sudoku Difficile',
    description: 'A complété une grille de sudoku en mode Difficile.',
    howToObtain: 'Termine une grille de sudoku en difficulté Difficile.',
    icon: '🧩',
    iconColor: '#faf5ff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#6d28d9', to: '#a855f7', direction: 'to bottom right' }),
    backgroundColor: '#6d28d9',
    borderColor: '#d8b4fe',
    category: 'achievement',
    rarity: 'rare',
    isAutomatic: true,
    autoConditionKey: 'SUDOKU_HARD',
  },
  {
    key: 'SUDOKU_EXPERT',
    name: 'Sudoku Expert',
    description: 'A complété une grille de sudoku en mode Expert. Chapeau.',
    howToObtain: 'Termine une grille de sudoku en difficulté Expert.',
    icon: '🧩',
    iconColor: '#fff1f2',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#991b1b', to: '#dc2626', direction: 'to bottom right' }),
    backgroundColor: '#991b1b',
    borderColor: '#fca5a5',
    category: 'achievement',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'SUDOKU_EXPERT',
  },

  // ── Casino ───────────────────────────────────────────────────────────────────
  {
    key: 'TOP_CASINO_LOSSES',
    name: 'Grande Ruine',
    description: 'A perdu le plus d\'argent au casino. Le casino remercie chaleureusement.',
    howToObtain: 'Être le joueur avec le plus de défaites au casino.',
    icon: '💸',
    iconColor: '#fbbf24',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#78350f', to: '#1c1917', direction: 'to bottom right' }),
    backgroundColor: '#78350f',
    borderColor: '#f59e0b',
    category: 'special',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'TOP_CASINO_LOSSES',
  },
  {
    key: 'TOP_CASINO_WINS',
    name: 'Patron du Casino',
    description: 'Cumule plus de victoires que tout le monde au casino.',
    howToObtain: 'Être le joueur avec le plus de victoires au casino.',
    icon: '♣️',
    iconColor: '#f0fdf4',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#14532d', to: '#15803d', direction: 'to bottom right' }),
    backgroundColor: '#14532d',
    borderColor: '#4ade80',
    category: 'special',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'TOP_CASINO_WINS',
  },
  {
    key: 'TOP_BADGES_COUNT',
    name: 'Collectionneur Supreme',
    description: 'Detient actuellement le plus grand nombre de badges.',
    howToObtain: 'Avoir plus de badges que tout le monde (egalite possible).',
    icon: '👑',
    iconColor: '#fde68a',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#0f172a', to: '#7c2d12', direction: 'to bottom right' }),
    backgroundColor: '#0f172a',
    borderColor: '#f59e0b',
    category: 'special',
    rarity: 'legendary',
    isAutomatic: true,
    autoConditionKey: 'TOP_BADGES_COUNT',
  },
  {
    key: 'CASINO_FIRST_PLAY',
    name: 'Premier Jeton',
    description: 'A tenté sa chance au casino pour la première fois.',
    howToObtain: 'Joue une partie au casino.',
    icon: '🪙',
    iconColor: '#fef3c7',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#78350f', to: '#b45309', direction: 'to bottom right' }),
    backgroundColor: '#78350f',
    borderColor: '#f59e0b',
    category: 'achievement',
    rarity: 'common',
    isAutomatic: true,
    autoConditionKey: 'CASINO_FIRST_PLAY',
  },
  {
    key: 'CASINO_REGULAR_10',
    name: 'Client Régulier',
    description: 'A joué 10 parties au casino. Le tapis commence à le reconnaître.',
    howToObtain: 'Joue 10 parties au casino.',
    icon: '🎟️',
    iconColor: '#fff7ed',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#92400e', to: '#78350f', direction: 'to bottom right' }),
    backgroundColor: '#92400e',
    borderColor: '#fbbf24',
    category: 'achievement',
    rarity: 'common',
    isAutomatic: true,
    autoConditionKey: 'CASINO_REGULAR_10',
  },
  {
    key: 'CASINO_VETERAN',
    name: 'Habitué du Casino',
    description: 'A joué 25 parties ou plus au casino. Le croupier le connaît par son prénom.',
    howToObtain: 'Joue 25 parties au casino.',
    icon: '🎰',
    iconColor: '#fbbf24',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#92400e', to: '#451a03', direction: 'to bottom right' }),
    backgroundColor: '#92400e',
    borderColor: '#d97706',
    category: 'achievement',
    rarity: 'uncommon',
    isAutomatic: true,
    autoConditionKey: 'CASINO_VETERAN',
  },
  {
    key: 'CASINO_REGULAR_50',
    name: 'Pilier du Casino',
    description: 'A joué 50 parties au casino. Il connaît chaque table par coeur.',
    howToObtain: 'Joue 50 parties au casino.',
    icon: '🎲',
    iconColor: '#fde68a',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#451a03', to: '#92400e', direction: 'to bottom right' }),
    backgroundColor: '#451a03',
    borderColor: '#f59e0b',
    category: 'achievement',
    rarity: 'rare',
    isAutomatic: true,
    autoConditionKey: 'CASINO_REGULAR_50',
  },
  {
    key: 'CASINO_REGULAR_100',
    name: 'Résident du Casino',
    description: 'A joué 100 parties au casino. À ce stade, il paie presque le loyer.',
    howToObtain: 'Joue 100 parties au casino.',
    icon: '🏛️',
    iconColor: '#fef3c7',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#1c1917', to: '#92400e', direction: 'to bottom right' }),
    backgroundColor: '#1c1917',
    borderColor: '#fbbf24',
    category: 'achievement',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'CASINO_REGULAR_100',
  },
  {
    key: 'CASINO_WIN_1',
    name: 'Ça Passe',
    description: 'A remporté sa première partie au casino.',
    howToObtain: 'Gagne une partie au casino.',
    icon: '🍀',
    iconColor: '#f0fdf4',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#166534', to: '#22c55e', direction: 'to bottom right' }),
    backgroundColor: '#166534',
    borderColor: '#86efac',
    category: 'achievement',
    rarity: 'common',
    isAutomatic: true,
    autoConditionKey: 'CASINO_WIN_1',
  },
  {
    key: 'CASINO_WIN_10',
    name: 'Main Chaude',
    description: 'A gagné 10 parties au casino.',
    howToObtain: 'Gagne 10 parties au casino.',
    icon: '🔥',
    iconColor: '#ecfdf5',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#166534', to: '#14532d', direction: 'to bottom right' }),
    backgroundColor: '#166534',
    borderColor: '#4ade80',
    category: 'achievement',
    rarity: 'uncommon',
    isAutomatic: true,
    autoConditionKey: 'CASINO_WIN_10',
  },
  {
    key: 'CASINO_WIN_25',
    name: 'Veine Insolente',
    description: 'A gagné 25 parties au casino. La chance abuse un peu.',
    howToObtain: 'Gagne 25 parties au casino.',
    icon: '♠️',
    iconColor: '#f0fdf4',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#14532d', to: '#064e3b', direction: 'to bottom right' }),
    backgroundColor: '#14532d',
    borderColor: '#6ee7b7',
    category: 'achievement',
    rarity: 'rare',
    isAutomatic: true,
    autoConditionKey: 'CASINO_WIN_25',
  },
  {
    key: 'CASINO_WIN_50',
    name: 'Croupier Cauchemar',
    description: 'A gagné 50 parties au casino. Le personnel le déteste.',
    howToObtain: 'Gagne 50 parties au casino.',
    icon: '👑',
    iconColor: '#f0fdf4',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#14532d', to: '#065f46', direction: 'to bottom right' }),
    backgroundColor: '#14532d',
    borderColor: '#a7f3d0',
    category: 'achievement',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'CASINO_WIN_50',
  },
  {
    key: 'CASINO_LOSS_1',
    name: 'Pas de Chance',
    description: 'A perdu sa première partie au casino.',
    howToObtain: 'Perds une partie au casino.',
    icon: '🥲',
    iconColor: '#fff1f2',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#7f1d1d', to: '#991b1b', direction: 'to bottom right' }),
    backgroundColor: '#7f1d1d',
    borderColor: '#f87171',
    category: 'achievement',
    rarity: 'common',
    isAutomatic: true,
    autoConditionKey: 'CASINO_LOSS_1',
  },
  {
    key: 'CASINO_LOSS_10',
    name: 'Chat Noir',
    description: 'A perdu 10 parties au casino.',
    howToObtain: 'Perds 10 parties au casino.',
    icon: '🐈',
    iconColor: '#fff1f2',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#7f1d1d', to: '#450a0a', direction: 'to bottom right' }),
    backgroundColor: '#7f1d1d',
    borderColor: '#fca5a5',
    category: 'achievement',
    rarity: 'uncommon',
    isAutomatic: true,
    autoConditionKey: 'CASINO_LOSS_10',
  },
  {
    key: 'CASINO_LOSS_25',
    name: 'Magnétiseur de Défaites',
    description: 'A perdu 25 parties au casino. Une vraie vocation.',
    howToObtain: 'Perds 25 parties au casino.',
    icon: '🫠',
    iconColor: '#fff7ed',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#7f1d1d', to: '#1f2937', direction: 'to bottom right' }),
    backgroundColor: '#7f1d1d',
    borderColor: '#f87171',
    category: 'achievement',
    rarity: 'rare',
    isAutomatic: true,
    autoConditionKey: 'CASINO_LOSS_25',
  },
  {
    key: 'CASINO_LOSS_50',
    name: 'Abonné aux Pertes',
    description: 'A perdu 50 parties au casino. Une fidélité coûteuse.',
    howToObtain: 'Perds 50 parties au casino.',
    icon: '💀',
    iconColor: '#fee2e2',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#450a0a', to: '#111827', direction: 'to bottom right' }),
    backgroundColor: '#450a0a',
    borderColor: '#f87171',
    category: 'achievement',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'CASINO_LOSS_50',
  },
  {
    key: 'CASINO_JACKPOT_50000',
    name: 'Jackpot 50K',
    description: 'A remporté 50 000$ ou plus en une seule partie au casino.',
    howToObtain: 'Gagne 50 000$ ou plus sur une partie de casino.',
    icon: '💰',
    iconColor: '#ecfeff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#065f46', to: '#0f766e', direction: 'to bottom right' }),
    backgroundColor: '#065f46',
    borderColor: '#5eead4',
    category: 'achievement',
    rarity: 'rare',
    isAutomatic: true,
    autoConditionKey: 'CASINO_JACKPOT_50000',
  },
  {
    key: 'CASINO_JACKPOT_100000',
    name: 'Jackpot 100K',
    description: 'A remporté 100 000$ ou plus en une seule partie au casino.',
    howToObtain: 'Gagne 100 000$ ou plus sur une partie de casino.',
    icon: '💎',
    iconColor: '#ecfeff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#0f172a', to: '#065f46', direction: 'to bottom right' }),
    backgroundColor: '#0f172a',
    borderColor: '#99f6e4',
    category: 'achievement',
    rarity: 'legendary',
    isAutomatic: true,
    autoConditionKey: 'CASINO_JACKPOT_100000',
  },

  // ── Other games ──────────────────────────────────────────────────────────────
  {
    key: 'FLAPPY_BIRD_50',
    name: 'Flappy Pro',
    description: 'A atteint 50 points à Flappy Bird. Ça tient du miracle.',
    howToObtain: 'Atteins un score de 50 à Flappy Bird.',
    icon: '🐦',
    iconColor: '#fef08a',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#0369a1', to: '#7dd3fc', direction: 'to bottom right' }),
    backgroundColor: '#0369a1',
    borderColor: '#38bdf8',
    category: 'achievement',
    rarity: 'rare',
    isAutomatic: true,
    autoConditionKey: 'FLAPPY_BIRD_50',
  },
  {
    key: 'MINESWEEPER_WIN',
    name: 'Déminer',
    description: 'A remporté une partie de Démineur sans exploser.',
    howToObtain: 'Gagne une partie de Démineur.',
    icon: '💣',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#374151', to: '#111827', direction: 'to bottom right' }),
    backgroundColor: '#374151',
    borderColor: '#6b7280',
    category: 'achievement',
    rarity: 'uncommon',
    isAutomatic: true,
    autoConditionKey: 'MINESWEEPER_WIN',
  },
  {
    key: 'MINESWEEPER_DEBUTANT',
    name: 'Démineur Débutant',
    description: 'A remporté une partie de Démineur en mode Débutant.',
    howToObtain: 'Gagne une partie de Démineur en difficulté Débutant.',
    icon: '💣',
    iconColor: '#f9fafb',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#374151', to: '#4b5563', direction: 'to bottom right' }),
    backgroundColor: '#374151',
    borderColor: '#9ca3af',
    category: 'achievement',
    rarity: 'common',
    isAutomatic: true,
    autoConditionKey: 'MINESWEEPER_DEBUTANT',
  },
  {
    key: 'MINESWEEPER_INTERMEDIAIRE',
    name: 'Démineur Intermédiaire',
    description: 'A remporté une partie de Démineur en mode Intermédiaire.',
    howToObtain: 'Gagne une partie de Démineur en difficulté Intermédiaire.',
    icon: '💣',
    iconColor: '#ecfdf5',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#065f46', to: '#059669', direction: 'to bottom right' }),
    backgroundColor: '#065f46',
    borderColor: '#34d399',
    category: 'achievement',
    rarity: 'uncommon',
    isAutomatic: true,
    autoConditionKey: 'MINESWEEPER_INTERMEDIAIRE',
  },
  {
    key: 'MINESWEEPER_EXPERT',
    name: 'Démineur Expert',
    description: 'A survécu au Démineur en mode Expert. Un héros.',
    howToObtain: 'Gagne une partie de Démineur en difficulté Expert.',
    icon: '💣',
    iconColor: '#fff7ed',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#7c2d12', to: '#ea580c', direction: 'to bottom right' }),
    backgroundColor: '#7c2d12',
    borderColor: '#fb923c',
    category: 'achievement',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'MINESWEEPER_EXPERT',
  },
  {
    key: 'SOLITAIRE_WIN',
    name: 'Solitaire Victorieux',
    description: 'A remporté une partie de Solitaire.',
    howToObtain: 'Gagne une partie de Solitaire.',
    icon: '🃏',
    iconColor: '#e0e7ff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#1e1b4b', to: '#3730a3', direction: 'to bottom right' }),
    backgroundColor: '#1e1b4b',
    borderColor: '#818cf8',
    category: 'achievement',
    rarity: 'uncommon',
    isAutomatic: true,
    autoConditionKey: 'SOLITAIRE_WIN',
  },
  {
    key: 'RACER_LAP',
    name: 'Lewis Hamilton',
    description: 'A complété un tour sur Racer. Vroom.',
    howToObtain: 'Termine un lap sur Racer.',
    icon: '🏎️',
    iconColor: '#fff7ed',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#7f1d1d', to: '#f97316', direction: 'to bottom right' }),
    backgroundColor: '#7f1d1d',
    borderColor: '#fb923c',
    category: 'achievement',
    rarity: 'common',
    isAutomatic: true,
    autoConditionKey: 'RACER_LAP',
  },
  {
    key: 'CHESS_WIN',
    name: 'Magnus Carlsen',
    description: 'A remporté une partie d\'échecs.',
    howToObtain: 'Gagne une partie d\'échecs.',
    icon: '♟️',
    iconColor: '#fafaf9',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#1c1917', to: '#44403c', direction: 'to bottom right' }),
    backgroundColor: '#1c1917',
    borderColor: '#a8a29e',
    category: 'achievement',
    rarity: 'uncommon',
    isAutomatic: true,
    autoConditionKey: 'CHESS_WIN',
  },
  {
    key: 'PUISSANCE_4_WIN',
    name: 'Puissant',
    description: 'A gagné une partie de Puissance 4.',
    howToObtain: 'Gagne une partie de Puissance 4.',
    icon: '🔴',
    iconColor: '#fff1f2',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#dc2626', to: '#b91c1c', direction: 'to bottom right' }),
    backgroundColor: '#dc2626',
    borderColor: '#fca5a5',
    category: 'achievement',
    rarity: 'common',
    isAutomatic: true,
    autoConditionKey: 'PUISSANCE_4_WIN',
  },
  {
    key: 'BALL_ARENA_WIN',
    name: 'Boulet de Canon',
    description: 'A expulsé son adversaire de l\'arène.',
    howToObtain: 'Gagne une partie de Ball Arena.',
    icon: '🎱',
    iconColor: '#ecfeff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#0e7490', to: '#06b6d4', direction: 'to bottom right' }),
    backgroundColor: '#0e7490',
    borderColor: '#67e8f9',
    category: 'achievement',
    rarity: 'common',
    isAutomatic: true,
    autoConditionKey: 'BALL_ARENA_WIN',
  },
  {
    key: 'GENEROUS',
    name: 'Généreux',
    description: 'A offert un cadeau à quelqu\'un. La générosité ça se mérite.',
    howToObtain: 'Offre un cadeau à un autre joueur.',
    icon: '🎁',
    iconColor: '#fff0f6',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#be185d', to: '#ec4899', direction: 'to bottom right' }),
    backgroundColor: '#be185d',
    borderColor: '#f9a8d4',
    category: 'achievement',
    rarity: 'uncommon',
    isAutomatic: true,
    autoConditionKey: 'GENEROUS',
  },
  {
    key: 'BUG_REPORTER',
    name: '☝️🤓',
    description: 'A reporté un bug. Techniquement utile.',
    howToObtain: 'Reporte un bug via le formulaire prévu à cet effet.',
    icon: '🐛',
    iconColor: '#f0fdf4',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#166534', to: '#15803d', direction: 'to bottom right' }),
    backgroundColor: '#166534',
    borderColor: '#4ade80',
    category: 'achievement',
    rarity: 'common',
    isAutomatic: true,
    autoConditionKey: 'BUG_REPORTER',
  },
  {
    key: 'NUIT_BLANCHE',
    name: 'Nuit Blanche',
    description: 'Connecté à 3h du matin. Les yeux rougis, le café chaud.',
    howToObtain: 'Connecte-toi entre 3h00 et 4h00 du matin.',
    icon: '🌙',
    iconColor: '#c7d2fe',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#0f172a', to: '#1e1b4b', direction: 'to bottom right' }),
    backgroundColor: '#0f172a',
    borderColor: '#4f46e5',
    category: 'achievement',
    rarity: 'rare',
    isAutomatic: true,
    autoConditionKey: 'NUIT_BLANCHE',
  },
  {
    key: 'CASINO_BET_10000',
    name: 'Gros Joueur',
    description: 'A misé 10 000$ ou plus en une seule mise au casino.',
    howToObtain: 'Place une mise d\'au moins 10 000$ au casino.',
    icon: '🎲',
    iconColor: '#fef3c7',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#78350f', to: '#d97706', direction: 'to bottom right' }),
    backgroundColor: '#78350f',
    borderColor: '#fbbf24',
    category: 'achievement',
    rarity: 'uncommon',
    isAutomatic: true,
    autoConditionKey: 'CASINO_BET_10000',
  },
  {
    key: 'CASINO_BET_20000',
    name: 'Grand Joueur',
    description: 'A misé 20 000$ ou plus en une seule mise au casino.',
    howToObtain: 'Place une mise d\'au moins 20 000$ au casino.',
    icon: '🃏',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#92400e', to: '#b45309', direction: 'to bottom right' }),
    backgroundColor: '#92400e',
    borderColor: '#f59e0b',
    category: 'achievement',
    rarity: 'rare',
    isAutomatic: true,
    autoConditionKey: 'CASINO_BET_20000',
  },
  {
    key: 'CASINO_BET_50000',
    name: 'Millionnaire du Casino',
    description: 'A misé 50 000$ ou plus en une seule mise. Les nerfs d\'acier.',
    howToObtain: 'Place une mise d\'au moins 50 000$ au casino.',
    icon: '💎',
    iconColor: '#e0e7ff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#1d4ed8', to: '#7c3aed', direction: 'to bottom right' }),
    backgroundColor: '#1d4ed8',
    borderColor: '#a78bfa',
    category: 'achievement',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'CASINO_BET_50000',
  },
  {
    key: 'CASINO_BET_100000',
    name: 'Roi du Casino',
    description: 'A misé 100 000$ ou plus en une seule mise. Légendaire.',
    howToObtain: 'Place une mise d\'au moins 100 000$ au casino.',
    icon: '👑',
    iconColor: '#fffbeb',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#b45309', to: '#f59e0b', direction: 'to bottom right' }),
    backgroundColor: '#b45309',
    borderColor: '#fde68a',
    category: 'achievement',
    rarity: 'legendary',
    isAutomatic: true,
    autoConditionKey: 'CASINO_BET_100000',
  },

  // ── Game champions (top highscore holders) ───────────────────────────────────
  {
    key: 'GAME_HIGHSCORE_DOODLE_JUMP',
    name: 'Champion Doodle Jump',
    description: 'Détient le meilleur score de Doodle Jump.',
    howToObtain: 'Avoir le meilleur score de Doodle Jump sur la plateforme.',
    icon: '🦘',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#166534', to: '#22c55e', direction: 'to bottom right' }),
    backgroundColor: '#166534',
    borderColor: '#4ade80',
    category: 'special',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'GAME_HIGHSCORE_DOODLE_JUMP',
  },
  {
    key: 'GAME_HIGHSCORE_DOODLE_JUMP_MORT_SUBITE',
    name: 'Champion Doodle Jump Mort Subite',
    description: 'Détient le meilleur score de Doodle Jump Mort Subite.',
    howToObtain: 'Avoir le meilleur score de Doodle Jump Mort Subite sur la plateforme.',
    icon: '💀',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#7f1d1d', to: '#ef4444', direction: 'to bottom right' }),
    backgroundColor: '#7f1d1d',
    borderColor: '#f87171',
    category: 'special',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'GAME_HIGHSCORE_DOODLE_JUMP_MORT_SUBITE',
  },
  {
    key: 'GAME_HIGHSCORE_GAME_2048',
    name: 'Champion 2048',
    description: 'Détient le meilleur score de 2048.',
    howToObtain: 'Avoir le meilleur score de 2048 sur la plateforme.',
    icon: '🔢',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#1e3a5f', to: '#3b82f6', direction: 'to bottom right' }),
    backgroundColor: '#1e3a5f',
    borderColor: '#60a5fa',
    category: 'special',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'GAME_HIGHSCORE_GAME_2048',
  },
  {
    key: 'GAME_HIGHSCORE_CHROME_DINO',
    name: 'Champion Chrome Dino',
    description: 'Détient le meilleur score de Chrome Dino.',
    howToObtain: 'Avoir le meilleur score de Chrome Dino sur la plateforme.',
    icon: '🦖',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#374151', to: '#9ca3af', direction: 'to bottom right' }),
    backgroundColor: '#374151',
    borderColor: '#d1d5db',
    category: 'special',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'GAME_HIGHSCORE_CHROME_DINO',
  },
  {
    key: 'GAME_HIGHSCORE_STACK_TOWER',
    name: 'Champion Stack Tower',
    description: 'Détient le meilleur score de Stack Tower.',
    howToObtain: 'Avoir le meilleur score de Stack Tower sur la plateforme.',
    icon: '🧱',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#78350f', to: '#f59e0b', direction: 'to bottom right' }),
    backgroundColor: '#78350f',
    borderColor: '#fbbf24',
    category: 'special',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'GAME_HIGHSCORE_STACK_TOWER',
  },
  {
    key: 'GAME_HIGHSCORE_GEOMETRY_DASH',
    name: 'Champion Geometry Dash',
    description: 'Détient le meilleur score de Geometry Dash.',
    howToObtain: 'Avoir le meilleur score de Geometry Dash sur la plateforme.',
    icon: '📐',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#4c1d95', to: '#8b5cf6', direction: 'to bottom right' }),
    backgroundColor: '#4c1d95',
    borderColor: '#c4b5fd',
    category: 'special',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'GAME_HIGHSCORE_GEOMETRY_DASH',
  },
  {
    key: 'GAME_HIGHSCORE_SOLITAIRE',
    name: 'Champion Solitaire',
    description: 'Détient le meilleur score de Solitaire.',
    howToObtain: 'Avoir le meilleur score de Solitaire sur la plateforme.',
    icon: '🃏',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#1e1b4b', to: '#6366f1', direction: 'to bottom right' }),
    backgroundColor: '#1e1b4b',
    borderColor: '#a5b4fc',
    category: 'special',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'GAME_HIGHSCORE_SOLITAIRE',
  },
  {
    key: 'GAME_HIGHSCORE_RACER',
    name: 'Champion Racer',
    description: 'Détient le meilleur temps sur Racer.',
    howToObtain: 'Avoir le meilleur temps de lap sur Racer.',
    icon: '🏎️',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#7f1d1d', to: '#f97316', direction: 'to bottom right' }),
    backgroundColor: '#7f1d1d',
    borderColor: '#fb923c',
    category: 'special',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'GAME_HIGHSCORE_RACER',
  },
  {
    key: 'GAME_HIGHSCORE_TETRIS',
    name: 'Champion Tetris',
    description: 'Détient le meilleur score de Tetris.',
    howToObtain: 'Avoir le meilleur score de Tetris sur la plateforme.',
    icon: '🧱',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#0c4a6e', to: '#38bdf8', direction: 'to bottom right' }),
    backgroundColor: '#0c4a6e',
    borderColor: '#7dd3fc',
    category: 'special',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'GAME_HIGHSCORE_TETRIS',
  },
  {
    key: 'GAME_HIGHSCORE_KNIFE_HIT',
    name: 'Champion Knife Hit',
    description: 'Détient le meilleur score de Knife Hit.',
    howToObtain: 'Avoir le meilleur score de Knife Hit sur la plateforme.',
    icon: '🔪',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#450a0a', to: '#dc2626', direction: 'to bottom right' }),
    backgroundColor: '#450a0a',
    borderColor: '#f87171',
    category: 'special',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'GAME_HIGHSCORE_KNIFE_HIT',
  },
  {
    key: 'GAME_HIGHSCORE_GOYAVE_EMPIRE',
    name: 'Champion Goyave Empire',
    description: 'Détient le meilleur score de Goyave Empire.',
    howToObtain: 'Avoir le meilleur score de Goyave Empire sur la plateforme.',
    icon: '🌿',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#365314', to: '#84cc16', direction: 'to bottom right' }),
    backgroundColor: '#365314',
    borderColor: '#bef264',
    category: 'special',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'GAME_HIGHSCORE_GOYAVE_EMPIRE',
  },
  {
    key: 'GAME_HIGHSCORE_LOGIC_LAB',
    name: 'Champion Logic Lab',
    description: 'Détient le meilleur score de Logic Lab.',
    howToObtain: 'Avoir le meilleur score de Logic Lab sur la plateforme.',
    icon: '🧠',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#1e3a5f', to: '#a5f3fc', direction: 'to bottom right' }),
    backgroundColor: '#1e3a5f',
    borderColor: '#67e8f9',
    category: 'special',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'GAME_HIGHSCORE_LOGIC_LAB',
  },
  {
    key: 'GAME_HIGHSCORE_MINESWEEPER',
    name: 'Champion Démineur',
    description: 'Détient le meilleur score de Démineur.',
    howToObtain: 'Avoir le meilleur score de Démineur sur la plateforme.',
    icon: '💣',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#374151', to: '#9ca3af', direction: 'to bottom right' }),
    backgroundColor: '#374151',
    borderColor: '#d1d5db',
    category: 'special',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'GAME_HIGHSCORE_MINESWEEPER',
  },
  {
    key: 'GAME_HIGHSCORE_FRUIT_NINJA',
    name: 'Ninja des Fruits',
    description: 'Détient le meilleur score de Fruit Ninja. Lame rapide, réflexes parfaits.',
    howToObtain: 'Avoir le meilleur score de Fruit Ninja sur la plateforme.',
    icon: '🍉',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#166534', to: '#dc2626', direction: 'to bottom right' }),
    backgroundColor: '#166534',
    borderColor: '#4ade80',
    category: 'special',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'GAME_HIGHSCORE_FRUIT_NINJA',
  },
  {
    key: 'GAME_HIGHSCORE_CASINO',
    name: 'Champion Casino',
    description: 'Détient le meilleur score de Casino.',
    howToObtain: 'Avoir la meilleure performance globale au Casino.',
    icon: '🎰',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#713f12', to: '#eab308', direction: 'to bottom right' }),
    backgroundColor: '#713f12',
    borderColor: '#facc15',
    category: 'special',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'GAME_HIGHSCORE_CASINO',
  },
  {
    key: 'BOMBPARTY_TOP_WINS',
    name: 'Champion Bomb Party',
    description: 'Le joueur avec le plus de victoires en Bomb Party.',
    howToObtain: 'Avoir le plus grand nombre de victoires en Bomb Party.',
    icon: '💥',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#7c2d12', to: '#fb923c', direction: 'to bottom right' }),
    backgroundColor: '#7c2d12',
    borderColor: '#fdba74',
    category: 'special',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'BOMBPARTY_TOP_WINS',
  },

  // ── Polymarket ───────────────────────────────────────────────────────────────
  {
    key: 'POLYMARKET_SUGGESTION_ACCEPTED',
    name: 'Visionnaire',
    description: 'A eu une suggestion Polymarket acceptée par les admins.',
    howToObtain: 'Soumets une suggestion Polymarket qui est approuvée.',
    icon: '💡',
    iconColor: '#fbbf24',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#1d4ed8', to: '#7c3aed', direction: 'to bottom right' }),
    backgroundColor: '#1d4ed8',
    borderColor: '#60a5fa',
    category: 'achievement',
    rarity: 'uncommon',
    isAutomatic: false,
    autoConditionKey: 'POLYMARKET_SUGGESTION_ACCEPTED',
  },
  {
    key: 'POLYMARKET_BETTOR',
    name: 'Parions Sport',
    description: 'A placé au moins un pari sur Polymarket.',
    howToObtain: 'Place un pari sur un événement Polymarket.',
    icon: '🎲',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#059669', to: '#065f46', direction: 'to bottom right' }),
    backgroundColor: '#059669',
    borderColor: '#34d399',
    category: 'achievement',
    rarity: 'common',
    isAutomatic: false,
    autoConditionKey: 'POLYMARKET_BETTOR',
  },
  {
    key: 'POLYMARKET_WIN',
    name: 'Oracle',
    description: "A gagné un pari sur Polymarket. L'avenir n'a pas de secrets pour lui.",
    howToObtain: 'Gagne un pari sur un événement Polymarket.',
    icon: '🔮',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#b45309', to: '#78350f', direction: 'to bottom right' }),
    backgroundColor: '#b45309',
    borderColor: '#fbbf24',
    category: 'achievement',
    rarity: 'uncommon',
    isAutomatic: false,
    autoConditionKey: 'POLYMARKET_WIN',
  },

  // ── New ideas set (manual award until dedicated logic is implemented) ─────
  {
    key: 'FIRST_STEP',
    name: 'Premier Pas',
    description: 'A terminé sa première quête quotidienne.',
    howToObtain: 'Termine 1 quête quotidienne.',
    icon: '👣',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#0ea5e9', to: '#2563eb', direction: 'to bottom right' }),
    backgroundColor: '#0ea5e9',
    borderColor: '#38bdf8',
    category: 'achievement',
    rarity: 'common',
    isAutomatic: false,
    autoConditionKey: 'FIRST_STEP',
  },
  {
    key: 'STREAK_7',
    name: 'Série de 7',
    description: 'A complété des objectifs quotidiens 7 jours d’affilée.',
    howToObtain: 'Complète tes dailies 7 jours consécutifs.',
    icon: '📅',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#2563eb', to: '#1d4ed8', direction: 'to bottom right' }),
    backgroundColor: '#2563eb',
    borderColor: '#60a5fa',
    category: 'achievement',
    rarity: 'uncommon',
    isAutomatic: true,
    autoConditionKey: 'STREAK_7',
  },
  {
    key: 'STREAK_30',
    name: 'Marathon 30',
    description: 'S’est connecté 30 jours de suite sans interruption.',
    howToObtain: 'Connecte-toi 30 jours consécutifs.',
    icon: '🗓️',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#1d4ed8', to: '#0f172a', direction: 'to bottom right' }),
    backgroundColor: '#1d4ed8',
    borderColor: '#93c5fd',
    category: 'achievement',
    rarity: 'rare',
    isAutomatic: true,
    autoConditionKey: 'STREAK_30',
  },
  {
    key: 'SPEEDRUN_DAILY_60S',
    name: 'Speedrunner',
    description: 'A validé une daily en moins d’une minute.',
    howToObtain: 'Termine une quête quotidienne en moins de 60 secondes.',
    icon: '⚡',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#f59e0b', to: '#dc2626', direction: 'to bottom right' }),
    backgroundColor: '#f59e0b',
    borderColor: '#fbbf24',
    category: 'achievement',
    rarity: 'rare',
    isAutomatic: false,
    autoConditionKey: 'SPEEDRUN_DAILY_60S',
  },
  {
    key: 'PERFECT_10',
    name: 'Sans Faute',
    description: 'A enchaîné 10 victoires consécutives.',
    howToObtain: 'Gagne 10 parties d’affilée sans perdre.',
    icon: '✅',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#16a34a', to: '#166534', direction: 'to bottom right' }),
    backgroundColor: '#16a34a',
    borderColor: '#4ade80',
    category: 'achievement',
    rarity: 'rare',
    isAutomatic: false,
    autoConditionKey: 'PERFECT_10',
  },
  {
    key: 'COMEBACK_WIN',
    name: 'Comeback',
    description: 'A remporté une partie après avoir été mené.',
    howToObtain: 'Gagne une partie après avoir été en difficulté.',
    icon: '🔄',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#7c3aed', to: '#4c1d95', direction: 'to bottom right' }),
    backgroundColor: '#7c3aed',
    borderColor: '#c4b5fd',
    category: 'achievement',
    rarity: 'uncommon',
    isAutomatic: false,
    autoConditionKey: 'COMEBACK_WIN',
  },
  {
    key: 'COLLECTIONNEUR_25',
    name: 'Collectionneur',
    description: 'A débloqué au moins 25 badges.',
    howToObtain: 'Obtiens 25 badges différents.',
    icon: '🏅',
    iconColor: '#fde68a',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#0f172a', to: '#334155', direction: 'to bottom right' }),
    backgroundColor: '#0f172a',
    borderColor: '#94a3b8',
    category: 'achievement',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'COLLECTIONNEUR_25',
  },
  {
    key: 'LEGEND_TOP10_WEEKLY',
    name: 'Légende',
    description: 'A terminé dans le top 10 du classement hebdomadaire.',
    howToObtain: 'Finis top 10 d’un classement hebdo.',
    icon: '🌟',
    iconColor: '#fde68a',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#7c2d12', to: '#1f2937', direction: 'to bottom right' }),
    backgroundColor: '#7c2d12',
    borderColor: '#f59e0b',
    category: 'special',
    rarity: 'epic',
    isAutomatic: false,
    autoConditionKey: 'LEGEND_TOP10_WEEKLY',
  },
  {
    key: 'KING_TOP3_MONTHLY',
    name: 'Roi du Mois',
    description: 'A terminé top 3 sur un classement mensuel.',
    howToObtain: 'Finis top 3 d’un classement mensuel.',
    icon: '👑',
    iconColor: '#fde68a',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#92400e', to: '#451a03', direction: 'to bottom right' }),
    backgroundColor: '#92400e',
    borderColor: '#f59e0b',
    category: 'special',
    rarity: 'legendary',
    isAutomatic: false,
    autoConditionKey: 'KING_TOP3_MONTHLY',
  },
  {
    key: 'SOCIAL_50_MESSAGES',
    name: 'Social Club',
    description: 'A envoyé 50 messages dans le chat.',
    howToObtain: 'Envoie 50 messages au total.',
    icon: '💬',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#0f766e', to: '#134e4a', direction: 'to bottom right' }),
    backgroundColor: '#0f766e',
    borderColor: '#2dd4bf',
    category: 'achievement',
    rarity: 'common',
    isAutomatic: true,
    autoConditionKey: 'SOCIAL_50_MESSAGES',
  },
  {
    key: 'MENTOR_3_REFERRALS',
    name: 'Mentor',
    description: 'A parrainé 3 nouveaux joueurs actifs.',
    howToObtain: 'Parraine 3 joueurs qui deviennent actifs.',
    icon: '🤝',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#0ea5e9', to: '#06b6d4', direction: 'to bottom right' }),
    backgroundColor: '#0ea5e9',
    borderColor: '#67e8f9',
    category: 'achievement',
    rarity: 'uncommon',
    isAutomatic: true,
    autoConditionKey: 'MENTOR_3_REFERRALS',
  },
  {
    key: 'GENEROUS_10_GIFTS',
    name: 'Généreux',
    description: 'A offert 10 cadeaux à d’autres joueurs.',
    howToObtain: 'Offre 10 cadeaux.',
    icon: '🎁',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#be123c', to: '#881337', direction: 'to bottom right' }),
    backgroundColor: '#be123c',
    borderColor: '#fb7185',
    category: 'achievement',
    rarity: 'uncommon',
    isAutomatic: true,
    autoConditionKey: 'GENEROUS_10_GIFTS',
  },
  {
    key: 'POLYMARKET_20_WINS',
    name: 'Stratège',
    description: 'A remporté 20 prédictions Polymarket.',
    howToObtain: 'Gagne 20 paris Polymarket.',
    icon: '📈',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#14532d', to: '#064e3b', direction: 'to bottom right' }),
    backgroundColor: '#14532d',
    borderColor: '#4ade80',
    category: 'achievement',
    rarity: 'rare',
    isAutomatic: true,
    autoConditionKey: 'POLYMARKET_20_WINS',
  },
  {
    key: 'CLAN_WARS_10',
    name: 'Esprit de Clan',
    description: 'A participé à 10 guerres de clan.',
    howToObtain: 'Participe à 10 guerres de clan.',
    icon: '🛡️',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#1f2937', to: '#111827', direction: 'to bottom right' }),
    backgroundColor: '#1f2937',
    borderColor: '#9ca3af',
    category: 'achievement',
    rarity: 'uncommon',
    isAutomatic: true,
    autoConditionKey: 'CLAN_WARS_10',
  },
  {
    key: 'CLAN_MVP_3',
    name: 'MVP de Clan',
    description: 'A terminé meilleur score de son clan 3 fois.',
    howToObtain: 'Sois MVP de ton clan à 3 reprises.',
    icon: '🏆',
    iconColor: '#fde68a',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#a16207', to: '#713f12', direction: 'to bottom right' }),
    backgroundColor: '#a16207',
    borderColor: '#facc15',
    category: 'special',
    rarity: 'epic',
    isAutomatic: true,
    autoConditionKey: 'CLAN_MVP_3',
  },
  {
    key: 'CHAMELEON_5_CLASSES',
    name: 'Caméléon',
    description: 'A gagné avec 5 classes différentes.',
    howToObtain: 'Gagne au moins une fois avec 5 classes distinctes.',
    icon: '🦎',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#0891b2', to: '#0f766e', direction: 'to bottom right' }),
    backgroundColor: '#0891b2',
    borderColor: '#22d3ee',
    category: 'achievement',
    rarity: 'rare',
    isAutomatic: false,
    autoConditionKey: 'CHAMELEON_5_CLASSES',
  },
  {
    key: 'NIGHT_OWL_WIN',
    name: 'Noctambule',
    description: 'A gagné une partie en pleine nuit.',
    howToObtain: 'Remporte une partie entre 2h et 5h.',
    icon: '🌙',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#312e81', to: '#0f172a', direction: 'to bottom right' }),
    backgroundColor: '#312e81',
    borderColor: '#a5b4fc',
    category: 'achievement',
    rarity: 'uncommon',
    isAutomatic: false,
    autoConditionKey: 'NIGHT_OWL_WIN',
  },
  {
    key: 'EARLY_BIRD_WIN',
    name: 'Lève-tôt',
    description: 'A gagné une partie avant 7h du matin.',
    howToObtain: 'Remporte une partie avant 7h.',
    icon: '🌅',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#f97316', to: '#ea580c', direction: 'to bottom right' }),
    backgroundColor: '#f97316',
    borderColor: '#fdba74',
    category: 'achievement',
    rarity: 'uncommon',
    isAutomatic: false,
    autoConditionKey: 'EARLY_BIRD_WIN',
  },
  {
    key: 'PERFECTIONIST_100',
    name: 'Perfectionniste',
    description: 'A complété 100 objectifs secondaires.',
    howToObtain: 'Valide 100 objectifs secondaires.',
    icon: '🎯',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#0f766e', to: '#134e4a', direction: 'to bottom right' }),
    backgroundColor: '#0f766e',
    borderColor: '#2dd4bf',
    category: 'achievement',
    rarity: 'rare',
    isAutomatic: false,
    autoConditionKey: 'PERFECTIONIST_100',
  },
  {
    key: 'MYTHIC_CATEGORY_COMPLETE',
    name: 'Mythique',
    description: 'A obtenu tous les badges d’une même catégorie.',
    howToObtain: 'Complète intégralement une catégorie de badges.',
    icon: '✨',
    iconColor: '#ffffff',
    backgroundType: 'gradient',
    backgroundGradient: JSON.stringify({ from: '#7c3aed', to: '#be185d', direction: 'to bottom right' }),
    backgroundColor: '#7c3aed',
    borderColor: '#e879f9',
    category: 'special',
    rarity: 'legendary',
    isAutomatic: true,
    autoConditionKey: 'MYTHIC_CATEGORY_COMPLETE',
  },
] as const;

// ─── Upsert logic ─────────────────────────────────────────────────────────────

async function main() {
  console.log('🏅 Seeding achievement badges...');
  let created = 0;
  let updated = 0;

  for (const badge of BADGES) {
    const { key, ...data } = badge;
    const existing = await prisma.badge.findFirst({
      where: { autoConditionKey: key },
    });

    if (existing) {
      await prisma.badge.update({
        where: { id: existing.id },
        data: { ...data, autoConditionKey: key },
      });
      updated++;
      console.log(`  ✏️  Updated: ${data.name}`);
    } else {
      await prisma.badge.create({
        data: { ...data, autoConditionKey: key },
      });
      created++;
      console.log(`  ✅ Created: ${data.name}`);
    }
  }

  console.log(`\n✨ Done — ${created} created, ${updated} updated.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
