ALTER TABLE "UpdatePopup" ADD COLUMN "type" TEXT NOT NULL DEFAULT 'UPDATE';
ALTER TABLE "UpdatePopup" ADD COLUMN "audience" TEXT NOT NULL DEFAULT 'ALL';
ALTER TABLE "UpdatePopup" ADD COLUMN "targetUserIds" TEXT NOT NULL DEFAULT '[]';
