import { ArrowDownCircle, ArrowLeftRight, ArrowUpCircle, AxeIcon, BarChart3, Briefcase, Building2, Coffee, CreditCard, Droplets, Flame, GraduationCap, Hammer, Landmark, Leaf, Scale, Scissors, ShieldAlert, ShieldOff, ShoppingBasket, Stethoscope, Store, TrendingUp, Trophy, UserPlus, Utensils, Video } from 'lucide-react';
import { type BusinessAction } from './types';

export const BUSINESS_ICON_MAP = {
  startup: Building2,
  bank: Landmark,
  agency: BarChart3,
  formation: GraduationCap,
  transfer: ArrowLeftRight,
  lemonade: Store,
  farm: Leaf,
  sawmill: AxeIcon,
  quarry: Hammer,
  iron_mine: Hammer,
  fuel_refinery: Flame,
  textile_mill: Scissors,
  epicerie: ShoppingBasket,
  restaurant: Utensils,
  coffee_shop: Coffee,
  youtube: Video,
  medecins: Stethoscope,
  horse_business: Trophy,
  illegal_market: ShieldAlert,
  supreme_court: Scale,
  law_firm: Briefcase,
  juterie: Droplets,
  labo_pub: ShieldOff,
} as const;

export const BUSINESS_STYLE_MAP = {
  startup: { card: 'border-border/30 bg-muted/10', badge: 'bg-muted/15 text-primary', iconWrap: 'bg-muted/15', icon: 'text-primary' },
  bank: { card: 'border-success/30 bg-success/10', badge: 'bg-success/15 text-success', iconWrap: 'bg-success/15', icon: 'text-success' },
  agency: { card: 'border-border/30 bg-muted/10', badge: 'bg-muted/15 text-primary', iconWrap: 'bg-muted/15', icon: 'text-primary' },
  formation: { card: 'border-warning/30 bg-warning/10', badge: 'bg-warning/15 text-warning', iconWrap: 'bg-warning/15', icon: 'text-warning' },
  transfer: { card: 'border-border/30 bg-muted/10', badge: 'bg-muted/15 text-primary', iconWrap: 'bg-muted/15', icon: 'text-primary' },
  lemonade: { card: 'border-warning/30 bg-warning/10', badge: 'bg-warning/15 text-warning', iconWrap: 'bg-warning/15', icon: 'text-warning' },
  farm: { card: 'border-success/30 bg-success/10', badge: 'bg-success/15 text-success', iconWrap: 'bg-success/15', icon: 'text-success' },
  sawmill: { card: 'border-warning/30 bg-warning/10', badge: 'bg-warning/15 text-warning', iconWrap: 'bg-warning/15', icon: 'text-warning' },
  quarry: { card: 'border-border/30 bg-secondary/10', badge: 'bg-secondary/15 text-muted-foreground', iconWrap: 'bg-secondary/15', icon: 'text-muted-foreground' },
  iron_mine: { card: 'border-border/30 bg-secondary/10', badge: 'bg-secondary/15 text-muted-foreground', iconWrap: 'bg-secondary/15', icon: 'text-muted-foreground' },
  fuel_refinery: { card: 'border-warning/30 bg-warning/10', badge: 'bg-warning/15 text-warning', iconWrap: 'bg-warning/15', icon: 'text-warning' },
  textile_mill: { card: 'border-destructive/30 bg-destructive/10', badge: 'bg-destructive/15 text-destructive', iconWrap: 'bg-destructive/15', icon: 'text-destructive' },
  epicerie: { card: 'border-success/30 bg-success/10', badge: 'bg-success/15 text-success', iconWrap: 'bg-success/15', icon: 'text-success' },
  restaurant: { card: 'border-destructive/30 bg-destructive/10', badge: 'bg-destructive/15 text-destructive', iconWrap: 'bg-destructive/15', icon: 'text-destructive' },
  coffee_shop: { card: 'border-warning/30 bg-warning/10', badge: 'bg-warning/15 text-warning', iconWrap: 'bg-warning/15', icon: 'text-warning' },
  youtube: { card: 'border-destructive/30 bg-destructive/10', badge: 'bg-destructive/15 text-destructive', iconWrap: 'bg-destructive/15', icon: 'text-destructive' },
  medecins: { card: 'border-success/30 bg-success/10', badge: 'bg-success/15 text-success', iconWrap: 'bg-success/15', icon: 'text-success' },
  horse_business: { card: 'border-border/30 bg-muted/10', badge: 'bg-muted/15 text-primary', iconWrap: 'bg-muted/15', icon: 'text-primary' },
  illegal_market: { card: 'border-border/30 bg-muted/10', badge: 'bg-muted/15 text-primary', iconWrap: 'bg-muted/15', icon: 'text-primary' },
  supreme_court: { card: 'border-border/30 bg-muted/10', badge: 'bg-muted/15 text-primary', iconWrap: 'bg-muted/15', icon: 'text-primary' },
  law_firm: { card: 'border-border/30 bg-muted/10', badge: 'bg-muted/15 text-primary', iconWrap: 'bg-muted/15', icon: 'text-primary' },
  juterie: { card: 'border-border/30 bg-muted/10', badge: 'bg-muted/15 text-primary', iconWrap: 'bg-muted/15', icon: 'text-primary' },
  labo_pub: { card: 'border-warning/30 bg-warning/10', badge: 'bg-warning/15 text-warning', iconWrap: 'bg-warning/15', icon: 'text-warning' },
} as const;

export const BUSINESS_COLOR_HEX: Record<string, string> = {
  lemonade: '#22c55e',
  farm: '#22c55e',
  sawmill: '#f59e0b',
  quarry: '#64748b',
  iron_mine: '#71717a',
  fuel_refinery: '#f97316',
  textile_mill: '#fb7185',
  restaurant: '#e11d48',
  coffee_shop: '#a16207',
  epicerie: '#84cc16',
  youtube: '#ef4444',
  medecins: '#10b981',
  horse_business: '#06b6d4',
  startup: '#3b82f6',
  agency: '#8b5cf6',
  bank: '#eab308',
  transfer: '#14b8a6',
  formation: '#6366f1',
  law_firm: '#06b6d4',
  illegal_market: '#dc2626',
  supreme_court: '#4f46e5',
  juterie: '#ec4899',
  labo_pub: '#f97316',
};

export const BUSINESS_MONO_MAP: Record<string, string> = {
  lemonade: 'LM', farm: 'FM', sawmill: 'SW', quarry: 'QR',
  iron_mine: 'IR', fuel_refinery: 'RF', textile_mill: 'TX',
  restaurant: 'RS', coffee_shop: 'CF', epicerie: 'EP',
  youtube: 'YT', medecins: 'MD', horse_business: 'HR', startup: 'ST', agency: 'AG',
  bank: 'BK', transfer: 'TR', formation: 'FO', law_firm: 'LW',
  illegal_market: 'IM', supreme_court: 'SC', juterie: 'JT', labo_pub: 'LP',
};

export const ACTION_META: Record<BusinessAction, { label: string; help: string; icon: typeof UserPlus; tone: string }> = {
  invite: { label: 'Inviter des joueurs', help: 'Envoyer des invitations de recrutement.', icon: UserPlus, tone: 'bg-muted/15 text-primary' },
  loan: { label: 'Demander un pret', help: 'Envoyer une demande de pret au proprietaire du business.', icon: CreditCard, tone: 'bg-warning/15 text-warning' },
  invest: { label: 'Investir', help: 'Transferer du money vers la tresorerie d un autre joueur.', icon: TrendingUp, tone: 'bg-muted/15 text-primary' },
  deposit: { label: 'Deposer', help: 'Envoyer ton argent personnel dans la tresorerie du business.', icon: ArrowDownCircle, tone: 'bg-success/15 text-success' },
  withdraw: { label: 'Retirer', help: 'Sortir du money de la tresorerie vers ton argent personnel.', icon: ArrowUpCircle, tone: 'bg-destructive/15 text-destructive' },
};
