import type { TutorialFlow } from '@/components/tutorial/types';

export const buildBusinessAToZ: TutorialFlow = {
  id: 'build-business-a-to-z',
  title: 'Construire un business de A à Z',
  description: 'Un parcours interactif complet: créer, placer, financer, produire, vendre, connecter et piloter une entreprise.',
  sections: [
    { id: 'setup', title: 'Cap', startIndex: 0, endIndex: 3 },
    { id: 'creation', title: 'Création', startIndex: 4, endIndex: 12 },
    { id: 'dashboard', title: 'Pilotage', startIndex: 13, endIndex: 18 },
    { id: 'supply', title: 'Supply', startIndex: 19, endIndex: 29 },
    { id: 'finance', title: 'Finance', startIndex: 30, endIndex: 34 },
  ],
  steps: [
    {
      id: 'mission',
      placement: 'center',
      title: 'Objectif: une vraie entreprise',
      content: (
        <div className="space-y-2">
          <p>On va construire une entreprise complète: capital, carte, production, prix, stock, contrats, risques et lecture financière.</p>
          <p className="text-muted-foreground">Ce guide avance quand tu cliques ou remplis les éléments demandés. Garde le rythme: chaque action sert ton business.</p>
        </div>
      ),
      route: '/you?tab=carte',
    },
    {
      id: 'dashboard-map',
      targetId: 'you-dashboard-map',
      placement: 'left',
      title: 'Le terrain de jeu',
      content: <p>La carte est le centre opérationnel: tu y places tes entreprises et tu surveilles ce qui vit autour de toi.</p>,
      route: '/you?tab=carte',
    },
    {
      id: 'left-rail',
      targetId: 'you-dashboard-left-rail',
      placement: 'right',
      title: 'Ton tableau de bord propriétaire',
      content: <p>Cette colonne suit ta trésorerie, ton net journalier, ton score de crédit, les intrants et les alertes de travail.</p>,
    },
    {
      id: 'create-from-dashboard',
      targetId: 'you-dashboard-create-business',
      placement: 'right',
      title: 'Lancer la création',
      content: <p>On commence par ouvrir le formulaire depuis ton empire.</p>,
      actionText: 'Clique sur « Créer ». Le guide continuera quand le formulaire apparaît.',
      advanceOn: 'target-click',
      advanceDelayMs: 700,
    },
    {
      id: 'modal-ready',
      targetId: 'create-business-modal',
      placement: 'auto',
      title: 'Formulaire de création',
      content: <p>Ici tu choisis l’activité, le nom et le capital. Chaque choix a un impact financier.</p>,
      advanceOn: 'target-present',
      advanceDelayMs: 900,
    },
    {
      id: 'open-type-picker',
      targetId: 'create-business-type',
      placement: 'auto',
      title: 'Choisir le secteur',
      content: <p>Le secteur décide de tes ressources, de tes revenus, de tes coûts et de tes futurs besoins d’approvisionnement.</p>,
      actionText: 'Clique sur le bloc du type d’activité.',
      advanceOn: 'target-click',
      advanceDelayMs: 500,
    },
    {
      id: 'select-lemonade',
      targetId: 'business-type-option-lemonade',
      placement: 'auto',
      title: 'Démarrage prudent',
      content: <p>Le stand de limonade est volontairement simple: peu de frais, production lisible, parfait pour apprendre les marges.</p>,
      actionText: 'Clique sur « Stand de limonade » ou choisis un autre niveau 1 si tu préfères.',
      advanceOn: 'target-click',
      advanceDelayMs: 350,
    },
    {
      id: 'confirm-type',
      targetId: 'business-type-picker-confirm',
      placement: 'left',
      title: 'Valider l’activité',
      content: <p>Confirme le secteur. Tu peux ensuite régler le capital et le nom.</p>,
      actionText: 'Clique sur le bouton de confirmation.',
      advanceOn: 'target-click',
      advanceDelayMs: 500,
    },
    {
      id: 'name-business',
      targetId: 'create-business-name',
      placement: 'auto',
      title: 'Nommer ton entreprise',
      content: <p>Le nom apparaîtra dans les contrats, les offres, la carte et le marché. Fais court, clair, reconnaissable.</p>,
      actionText: 'Tape un nom pour continuer.',
      advanceOn: 'target-input',
      advanceDelayMs: 500,
    },
    {
      id: 'capital-business',
      targetId: 'create-business-capital',
      placement: 'auto',
      title: 'Capital de départ',
      content: <p>Le capital devient ta trésorerie. Il finance les premiers jours, les salaires, les achats de ressources et les coûts logistiques.</p>,
      actionText: 'Ajuste le capital si le champ est présent.',
      requireManualAdvance: true,
    },
    {
      id: 'submit-business',
      targetId: 'create-business-submit',
      placement: 'left',
      title: 'Créer officiellement',
      content: <p>Quand le bouton est actif, tu peux valider. Le business entrera dans ton empire.</p>,
      actionText: 'Clique sur « Créer ». Le guide attendra le retour à la liste.',
      advanceOn: 'target-click',
      advanceDelayMs: 1200,
    },
    {
      id: 'owned-business-list',
      targetId: 'travail-owned-businesses',
      placement: 'auto',
      title: 'Vérifier la création',
      content: <p>Ton entreprise doit apparaître ici. Ouvre-la plus tard pour gérer l’équipe, les dépôts, retraits, menus et actions propres au secteur.</p>,
      route: '/you?tab=travail',
    },
    {
      id: 'back-to-dashboard',
      targetId: 'you-tab-carte',
      placement: 'right',
      title: 'Retour au cockpit',
      content: <p>On passe au pilotage réel: carte, placement, indicateurs financiers et production.</p>,
      actionText: 'Clique sur l’onglet Carte.',
      advanceOn: 'target-click',
      advanceDelayMs: 700,
    },
    {
      id: 'business-card-finance',
      targetId: 'you-dashboard-owned-business-card',
      placement: 'right',
      title: 'Lire la carte financière',
      content: <p>Regarde le net par jour, le runway, le crédit et les intrants. Si le net est négatif ou le runway court, ta priorité est la trésorerie.</p>,
      route: '/you?tab=carte',
    },
    {
      id: 'place-business',
      targetId: 'you-dashboard-place-business',
      placement: 'right',
      title: 'Placer sur la carte',
      content: <p>Si ton entreprise n’est pas encore placée, utilise ce bouton puis clique sur la carte. Le placement rend l’empire plus concret.</p>,
      actionText: 'Clique sur « Placer » si le bouton est visible, puis clique sur la carte.',
      requireManualAdvance: true,
    },
    {
      id: 'map-click-place',
      targetId: 'you-dashboard-map',
      placement: 'left',
      title: 'Choisir l’emplacement',
      content: <p>Un bon emplacement aide à lire ton réseau. Place les producteurs près des clients que tu veux approvisionner.</p>,
      actionText: 'Clique sur la carte pour confirmer un emplacement si tu es en mode placement.',
      requireManualAdvance: true,
    },
    {
      id: 'work-warning',
      targetId: 'you-dashboard-work-button',
      placement: 'right',
      title: 'Travail quotidien',
      content: <p>Les entreprises productrices dépendent de l’équipe. Plus les membres travaillent, plus la production monte, avec un bonus à 4 personnes actives.</p>,
      actionText: 'Si le bouton existe, clique pour faire le mini-jeu de travail. Sinon continue.',
      requireManualAdvance: true,
    },
    {
      id: 'news-feed',
      targetId: 'you-dashboard-left-rail',
      placement: 'right',
      title: 'Priorités de propriétaire',
      content: <p>Chaque jour, regarde dans cet ordre: cash, runway, intrants, offres en attente, travail requis. C’est ta checklist anti-faillite.</p>,
    },
    {
      id: 'go-supply',
      targetId: 'you-tab-supply',
      placement: 'right',
      title: 'Passer au supply',
      content: <p>La supply chain transforme ton business en système: stock, prix, contrats, sourcing et ventes automatiques.</p>,
      actionText: 'Clique sur l’onglet Supply.',
      advanceOn: 'target-click',
      advanceDelayMs: 800,
    },
    {
      id: 'supply-register',
      targetId: 'supply-businesses-sidebar',
      placement: 'right',
      title: 'Registre des entreprises',
      content: <p>Sélectionne ici l’entreprise à piloter. Les jauges montrent stock, chantier, demandes et alertes de travail.</p>,
      route: '/you?tab=supply',
    },
    {
      id: 'finance-strip',
      targetId: 'supply-finance-strip',
      placement: 'bottom',
      title: 'P&L instantané',
      content: <p>Ce bandeau résume la santé: net journalier, score de crédit et couverture d’intrants. C’est ton feu tricolore financier.</p>,
    },
    {
      id: 'supply-node',
      targetId: 'supply-inventory-node',
      placement: 'auto',
      title: 'Ouvrir un dépôt',
      content: <p>Chaque dépôt a quantité, capacité, production horaire, prix global et prix joueur. C’est ici que la marge se décide.</p>,
      actionText: 'Clique sur un dépôt de ressource.',
      advanceOn: 'target-click',
      advanceDelayMs: 700,
    },
    {
      id: 'financial-panel',
      targetId: 'supply-financial-panel',
      placement: 'auto',
      title: 'Lire le risque avant d’agir',
      content: <p>Avant de publier une offre, vérifie le P&L, le runway, le risque et l’événement du jour. Un pic de demande peut justifier un prix plus haut.</p>,
    },
    {
      id: 'price-field',
      targetId: 'supply-offer-submit',
      placement: 'auto',
      title: 'Publier une offre',
      content: <p>Le panneau compare ton prix au marché, estime la marge et montre le prix de liquidation globale. Vise une marge positive sans bloquer les ventes.</p>,
      actionText: 'Ajuste le prix si besoin, puis publie ou mets à jour l’offre.',
      requireManualAdvance: true,
    },
    {
      id: 'market-panel',
      targetId: 'supply-market-panel',
      placement: 'left',
      title: 'Acheter aux autres joueurs',
      content: <p>Ce marché liste les sources disponibles. Les contrats créent de vrais flux d’argent et de stock entre entreprises.</p>,
    },
    {
      id: 'orders-panel',
      targetId: 'supply-orders-sidebar',
      placement: 'left',
      title: 'Répondre aux demandes',
      content: <p>Accepter une demande engage ton stock, mais crée un revenu futur. Refuser protège ton inventaire et ta fiabilité quand tu ne peux pas livrer.</p>,
    },
    {
      id: 'link-inventory',
      targetId: 'supply-inventory-node',
      placement: 'auto',
      title: 'Automatiser prudemment',
      content: <p>Survole un dépôt: les poignées permettent de relier un stock à une autre entreprise ou au marché global. Les liens internes ont maintenant un coût logistique.</p>,
      actionText: 'Essaie de tirer une liaison vers une cible compatible, ou continue si tu veux garder la main.',
      requireManualAdvance: true,
    },
    {
      id: 'global-market',
      targetId: 'supply-global-market-node',
      placement: 'left',
      title: 'Vente de secours',
      content: <p>Le marché global liquide vite, mais à prix cassé. Utilise-le pour vider un stock plein, pas comme stratégie principale.</p>,
    },
    {
      id: 'full-view',
      targetId: 'supply-nodes-pane',
      placement: 'top',
      title: 'Penser réseau',
      content: <p>Quand tu possèdes plusieurs entreprises, passe en vue totale et connecte producteurs, clients et chantiers. Le but: moins de stock mort, plus de marge.</p>,
    },
    {
      id: 'credit-score',
      targetId: 'supply-finance-strip',
      placement: 'bottom',
      title: 'Préparer le financement',
      content: <p>Le score de crédit combine cash, dette, fiabilité, satisfaction et runway. Plus il est haut, plus les banques peuvent te faire confiance.</p>,
    },
    {
      id: 'finance-tab',
      targetId: 'you-tab-finance',
      placement: 'right',
      title: 'Contrôler les comptes',
      content: <p>La finance consolide transactions, banques, dettes et cash personnel. C’est là que tu vérifies si la croissance reste saine.</p>,
      actionText: 'Clique sur Finance.',
      advanceOn: 'target-click',
      advanceDelayMs: 700,
    },
    {
      id: 'share-market',
      targetId: 'you-tab-marche-actions',
      placement: 'right',
      title: 'Lever ou sortir du capital',
      content: <p>Le marché d’actions permet de vendre une part, acheter une participation ou valoriser une entreprise selon ses revenus et sa trésorerie.</p>,
      actionText: 'Tu peux ouvrir le marché actions maintenant ou continuer.',
      requireManualAdvance: true,
    },
    {
      id: 'final-loop',
      placement: 'center',
      title: 'La boucle complète',
      content: (
        <div className="space-y-2">
          <p>Ta routine propriétaire est prête: produire, couvrir les intrants, fixer les prix, accepter les bons contrats, financer la croissance et surveiller le risque.</p>
          <p className="text-muted-foreground">Quand un chiffre devient rouge, il dit quoi faire: cash court, intrants faibles, prix trop haut, dette lourde ou fournisseur peu fiable.</p>
        </div>
      ),
      route: '/you?tab=carte',
    },
  ],
};
