ALTER TABLE "Clan"
ADD COLUMN "warTrophies" INTEGER NOT NULL DEFAULT 1000;

ALTER TABLE "Clan"
ADD COLUMN "warWins" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Clan"
ADD COLUMN "warLosses" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Clan"
ADD COLUMN "warDraws" INTEGER NOT NULL DEFAULT 0;

CREATE INDEX "Clan_warTrophies_idx" ON "Clan"("warTrophies");

ALTER TABLE "ClanWar"
ADD COLUMN "attackerTrophiesBefore" INTEGER NOT NULL DEFAULT 1000;

ALTER TABLE "ClanWar"
ADD COLUMN "defenderTrophiesBefore" INTEGER NOT NULL DEFAULT 1000;

ALTER TABLE "ClanWar"
ADD COLUMN "attackerTrophyChange" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "ClanWar"
ADD COLUMN "defenderTrophyChange" INTEGER NOT NULL DEFAULT 0;
