/**
 * Default automatic badge definitions.
 * Run ensureDefaultBadges() at server startup — it is fully idempotent:
 * badges are identified by autoConditionKey and will be created only if missing.
 */

import { prisma } from '../server.js';

// ─── Visual presets ───────────────────────────────────────────────────────────

const GRAD = (from: string, to: string, direction = 'to bottom right') =>
  JSON.stringify({ from, to, direction });

const LEGENDARY = {
  backgroundType: 'gradient',
  backgroundGradient: GRAD('#b45309', '#f59e0b'),
  backgroundColor: '#b45309',
  borderColor: '#f59e0b',
  iconColor: '#fff7ed',
  rarity: 'legendary',
};

const EPIC = {
  backgroundType: 'gradient',
  backgroundGradient: GRAD('#6d28d9', '#a855f7'),
  backgroundColor: '#6d28d9',
  borderColor: '#a855f7',
  iconColor: '#faf5ff',
  rarity: 'epic',
};

const RARE = {
  backgroundType: 'gradient',
  backgroundGradient: GRAD('#1d4ed8', '#3b82f6'),
  backgroundColor: '#1d4ed8',
  borderColor: '#60a5fa',
  iconColor: '#eff6ff',
  rarity: 'rare',
};

const UNCOMMON = {
  backgroundType: 'gradient',
  backgroundGradient: GRAD('#15803d', '#22c55e'),
  backgroundColor: '#15803d',
  borderColor: '#4ade80',
  iconColor: '#f0fdf4',
  rarity: 'uncommon',
};

// Unique gradient per game champion badge
const GAME_GRAD: Record<string, { from: string; to: string }> = {
  doodle_jump:              { from: '#166534', to: '#22c55e' },
  doodle_jump_mort_subite:  { from: '#7f1d1d', to: '#ef4444' },
  flappy_bird:              { from: '#92400e', to: '#f59e0b' },
  game_2048:                { from: '#1e3a5f', to: '#3b82f6' },
  snake:                    { from: '#14532d', to: '#4ade80' },
  geometry_dash:            { from: '#4c1d95', to: '#8b5cf6' },
  solitaire:                { from: '#1e1b4b', to: '#6366f1' },
  racer:                    { from: '#7f1d1d', to: '#f97316' },
  tetris:                   { from: '#0c4a6e', to: '#38bdf8' },
  knife_hit:                { from: '#450a0a', to: '#dc2626' },
  goyave_empire:            { from: '#365314', to: '#84cc16' },
  logic_lab:                { from: '#1e3a5f', to: '#a5f3fc' },
  minesweeper:              { from: '#374151', to: '#9ca3af' },
  casino:                   { from: '#713f12', to: '#eab308' },
  bombparty:                { from: '#7c2d12', to: '#fb923c' },
};

const GAME_ICON: Record<string, string> = {
  doodle_jump:             '🦘',
  doodle_jump_mort_subite: '💀',
  flappy_bird:             '🐦',
  game_2048:               '🔢',
  snake:                   '🐍',
  geometry_dash:           '📐',
  solitaire:               '🃏',
  racer:                   '🏎️',
  tetris:                  '🧱',
  knife_hit:               '🔪',
  goyave_empire:           '🌿',
  logic_lab:               '🧠',
  minesweeper:             '💣',
  casino:                  '🎰',
  bombparty:               '💥',
};

const GAME_LABEL: Record<string, string> = {
  doodle_jump:             'Doodle Jump',
  doodle_jump_mort_subite: 'Doodle Jump Mort Subite',
  flappy_bird:             'Flappy Bird',
  game_2048:               '2048',
  snake:                   'Snake',
  geometry_dash:           'Geometry Dash',
  solitaire:               'Solitaire',
  racer:                   'Racer',
  tetris:                  'Tetris',
  knife_hit:               'Knife Hit',
  goyave_empire:           'Goyave Empire',
  logic_lab:               'Logic Lab',
  minesweeper:             'Démineur',
  casino:                  'Casino',
  bombparty:               'Bomb Party',
};

// ─── Badge definitions ────────────────────────────────────────────────────────

interface BadgeDef {
  autoConditionKey: string;
  name: string;
  description: string;
  howToObtain: string;
  icon: string;
  category: string;
  backgroundType: string;
  backgroundColor: string;
  backgroundGradient?: string;
  borderColor: string;
  iconColor: string;
  rarity: string;
  isHidden?: boolean;
}

const AURA_BADGES: BadgeDef[] = [
  {
    autoConditionKey: 'TOP_1_AURA',
    name: '#1 Aura',
    description: 'Le joueur avec le plus d\'aura sur toute la plateforme.',
    howToObtain: 'Avoir le plus d\'aura parmi tous les joueurs.',
    icon: '👑',
    category: 'leaderboard',
    ...LEGENDARY,
  },
  {
    autoConditionKey: 'TOP_3_AURA',
    name: 'Top 3 Aura',
    description: 'Parmi les 3 joueurs avec le plus d\'aura.',
    howToObtain: 'Être dans le top 3 du classement aura.',
    icon: '✨',
    category: 'leaderboard',
    ...EPIC,
  },
  {
    autoConditionKey: 'TOP_5_AURA',
    name: 'Top 5 Aura',
    description: 'Parmi les 5 joueurs avec le plus d\'aura.',
    howToObtain: 'Être dans le top 5 du classement aura.',
    icon: '⚡',
    category: 'leaderboard',
    ...RARE,
  },
  {
    autoConditionKey: 'TOP_10_AURA',
    name: 'Top 10 Aura',
    description: 'Parmi les 10 joueurs avec le plus d\'aura.',
    howToObtain: 'Être dans le top 10 du classement aura.',
    icon: '🌟',
    category: 'leaderboard',
    ...UNCOMMON,
  },
];

const MONEY_BADGES: BadgeDef[] = [
  {
    autoConditionKey: 'TOP_1_MONEY',
    name: '#1 Argent',
    description: 'Le joueur le plus riche de la plateforme.',
    howToObtain: 'Avoir le plus d\'argent parmi tous les joueurs.',
    icon: '💎',
    category: 'leaderboard',
    ...LEGENDARY,
  },
  {
    autoConditionKey: 'TOP_3_MONEY',
    name: 'Top 3 Argent',
    description: 'Parmi les 3 joueurs les plus riches.',
    howToObtain: 'Être dans le top 3 du classement argent.',
    icon: '💰',
    category: 'leaderboard',
    ...EPIC,
  },
  {
    autoConditionKey: 'TOP_5_MONEY',
    name: 'Top 5 Argent',
    description: 'Parmi les 5 joueurs les plus riches.',
    howToObtain: 'Être dans le top 5 du classement argent.',
    icon: '💵',
    category: 'leaderboard',
    ...RARE,
  },
  {
    autoConditionKey: 'TOP_10_MONEY',
    name: 'Top 10 Argent',
    description: 'Parmi les 10 joueurs les plus riches.',
    howToObtain: 'Être dans le top 10 du classement argent.',
    icon: '🪙',
    category: 'leaderboard',
    ...UNCOMMON,
  },
];

const GAME_CONDITION_KEYS = [
  'doodle_jump', 'doodle_jump_mort_subite',
  'flappy_bird', 'game_2048', 'snake', 'geometry_dash',
  'solitaire', 'racer',
  'tetris', 'knife_hit', 'goyave_empire',
  'logic_lab', 'minesweeper', 'casino',
];

const GAME_BADGES: BadgeDef[] = GAME_CONDITION_KEYS.map((gameType) => {
  const g = GAME_GRAD[gameType] ?? { from: '#374151', to: '#6b7280' };
  const label = GAME_LABEL[gameType] ?? gameType;
  const isRacer = gameType === 'racer';
  return {
    autoConditionKey: `GAME_HIGHSCORE_${gameType}`,
    name: `Champion ${label}`,
    description: `${isRacer ? 'Le meilleur temps sur' : 'Le meilleur score sur'} ${label}.`,
    howToObtain: `${isRacer ? 'Avoir le meilleur temps de lap' : 'Avoir le meilleur score'} sur ${label}.`,
    icon: GAME_ICON[gameType] ?? '🏆',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD(g.from, g.to),
    backgroundColor: g.from,
    borderColor: g.to,
    iconColor: '#ffffff',
    rarity: 'epic',
  };
});

const BOMBPARTY_BADGE: BadgeDef = {
  autoConditionKey: 'BOMBPARTY_TOP_WINS',
  name: 'Champion Bomb Party',
  description: 'Le joueur avec le plus de victoires en Bomb Party.',
  howToObtain: 'Avoir le plus grand nombre de victoires en Bomb Party.',
  icon: GAME_ICON.bombparty,
  category: 'achievement',
  backgroundType: 'gradient',
  backgroundGradient: GRAD(GAME_GRAD.bombparty.from, GAME_GRAD.bombparty.to),
  backgroundColor: GAME_GRAD.bombparty.from,
  borderColor: GAME_GRAD.bombparty.to,
  iconColor: '#ffffff',
  rarity: 'epic',
};

// ─── Membre AuraTracker ───────────────────────────────────────────────────────

const MEMBER_BADGE: BadgeDef = {
  autoConditionKey: 'MEMBER',
  name: 'Membre AuraTracker',
  description: 'Membre officiel de la communauté AuraTracker.',
  howToObtain: 'Avoir un compte approuvé sur AuraTracker.',
  icon: '🔰',
  category: 'special',
  backgroundType: 'gradient',
  backgroundGradient: GRAD('#0f766e', '#14b8a6'),
  backgroundColor: '#0f766e',
  borderColor: '#2dd4bf',
  iconColor: '#f0fdfa',
  rarity: 'uncommon',
};

// ─── Class badges (3 levels × 7 letters = 21 badges) ─────────────────────────

const LEVEL_GRAD: Record<string, { from: string; to: string; border: string }> = {
  SECONDE:    { from: '#1e3a8a', to: '#3b82f6', border: '#93c5fd' },
  PREMIERE:   { from: '#92400e', to: '#f59e0b', border: '#fcd34d' },
  TERMINALE:  { from: '#7f1d1d', to: '#ef4444', border: '#fca5a5' },
};

const LEVEL_LABEL: Record<string, string> = {
  SECONDE:   'Seconde',
  PREMIERE:  'Première',
  TERMINALE: 'Terminale',
};

const CLASS_LETTERS = ['A', 'B', 'C', 'D', 'E', 'F', 'G'] as const;
const LEVELS = ['SECONDE', 'PREMIERE', 'TERMINALE'] as const;

const CLASS_BADGES: BadgeDef[] = LEVELS.flatMap((level) =>
  CLASS_LETTERS.map((letter): BadgeDef => {
    const g = LEVEL_GRAD[level];
    return {
      autoConditionKey: `CLASS_${level}_${letter}`,
      name: `${LEVEL_LABEL[level]} ${letter}`,
      description: `Élève en ${LEVEL_LABEL[level]} ${letter}.`,
      howToObtain: `Être inscrit en ${LEVEL_LABEL[level]} ${letter}.`,
      icon: letter,
      category: 'special',
      backgroundType: 'gradient',
      backgroundGradient: GRAD(g.from, g.to),
      backgroundColor: g.from,
      borderColor: g.border,
      iconColor: '#ffffff',
      rarity: 'common',
    };
  }),
);

// ─── Achievement badges ───────────────────────────────────────────────────────

const ACHIEVEMENT_BADGES: BadgeDef[] = [
  {
    autoConditionKey: 'TRYHARDEUR',
    name: 'Tryhardeur',
    description: 'A joué plus de 100 parties au total, tous jeux confondus.',
    howToObtain: 'Joue 100 parties sur n\'importe quel jeu de la plateforme.',
    icon: '💪',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#f97316', '#dc2626'),
    backgroundColor: '#f97316',
    borderColor: '#f97316',
    iconColor: '#ffffff',
    rarity: 'uncommon',
  },
  {
    autoConditionKey: 'GRIND_200',
    name: 'No Life',
    description: 'A joué plus de 200 parties au total. Il a vraiment rien d\'autre à faire.',
    howToObtain: 'Joue 200 parties sur n\'importe quel jeu.',
    icon: '🔥',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#991b1b', '#7c3aed'),
    backgroundColor: '#991b1b',
    borderColor: '#ef4444',
    iconColor: '#ffffff',
    rarity: 'rare',
  },
  {
    autoConditionKey: 'GAME_2048_TILE_2048',
    name: '2048',
    description: 'A accompli la tuile 2048 dans le jeu du même nom.',
    howToObtain: 'Atteins la tuile 2048 dans le jeu 2048.',
    icon: '🎯',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#1d4ed8', '#7c3aed'),
    backgroundColor: '#1d4ed8',
    borderColor: '#60a5fa',
    iconColor: '#fbbf24',
    rarity: 'rare',
  },
  {
    autoConditionKey: 'GAME_2048_TILE_4096',
    name: '4096',
    description: 'A atteint la légendaire tuile 4096. Un vrai génie des chiffres.',
    howToObtain: 'Atteins la tuile 4096 dans le jeu 2048.',
    icon: '🧠',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#4c1d95', '#0f172a'),
    backgroundColor: '#4c1d95',
    borderColor: '#c084fc',
    iconColor: '#ffffff',
    rarity: 'epic',
  },
  {
    autoConditionKey: 'SUDOKU_COMPLETED',
    name: 'Sudokiste',
    description: 'A complété une grille de sudoku. La logique ne lui fait pas peur.',
    howToObtain: 'Termine une grille de sudoku.',
    icon: '🧩',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#065f46', '#0f766e'),
    backgroundColor: '#065f46',
    borderColor: '#34d399',
    iconColor: '#ffffff',
    rarity: 'uncommon',
  },
  {
    autoConditionKey: 'TOP_CASINO_LOSSES',
    name: 'Grande Ruine',
    description: 'A perdu le plus d\'argent au casino. Le casino remercie chaleureusement.',
    howToObtain: 'Être le joueur avec le plus de défaites au casino.',
    icon: '💸',
    category: 'special',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#78350f', '#1c1917'),
    backgroundColor: '#78350f',
    borderColor: '#f59e0b',
    iconColor: '#fbbf24',
    rarity: 'epic',
  },
  {
    autoConditionKey: 'TOP_CASINO_WINS',
    name: 'Patron du Casino',
    description: 'Cumule plus de victoires que tout le monde au casino.',
    howToObtain: 'Être le joueur avec le plus de victoires au casino.',
    icon: '♣️',
    category: 'special',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#14532d', '#15803d'),
    backgroundColor: '#14532d',
    borderColor: '#4ade80',
    iconColor: '#f0fdf4',
    rarity: 'epic',
  },
  {
    autoConditionKey: 'CASINO_FIRST_PLAY',
    name: 'Premier Jeton',
    description: 'A tenté sa chance au casino pour la première fois.',
    howToObtain: 'Joue une partie au casino.',
    icon: '🪙',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#78350f', '#b45309'),
    backgroundColor: '#78350f',
    borderColor: '#f59e0b',
    iconColor: '#fef3c7',
    rarity: 'common',
  },
  {
    autoConditionKey: 'CASINO_REGULAR_10',
    name: 'Client Régulier',
    description: 'A joué 10 parties au casino. Le tapis commence à le reconnaître.',
    howToObtain: 'Joue 10 parties au casino.',
    icon: '🎟️',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#92400e', '#78350f'),
    backgroundColor: '#92400e',
    borderColor: '#fbbf24',
    iconColor: '#fff7ed',
    rarity: 'common',
  },
  {
    autoConditionKey: 'CASINO_VETERAN',
    name: 'Habitué du Casino',
    description: 'A joué 25 parties ou plus au casino. Le croupier le connaît par son prénom.',
    howToObtain: 'Joue 25 parties au casino.',
    icon: '🎰',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#92400e', '#451a03'),
    backgroundColor: '#92400e',
    borderColor: '#d97706',
    iconColor: '#fbbf24',
    rarity: 'uncommon',
  },
  {
    autoConditionKey: 'CASINO_REGULAR_50',
    name: 'Pilier du Casino',
    description: 'A joué 50 parties au casino. Il connaît chaque table par coeur.',
    howToObtain: 'Joue 50 parties au casino.',
    icon: '🎲',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#451a03', '#92400e'),
    backgroundColor: '#451a03',
    borderColor: '#f59e0b',
    iconColor: '#fde68a',
    rarity: 'rare',
  },
  {
    autoConditionKey: 'CASINO_REGULAR_100',
    name: 'Résident du Casino',
    description: 'A joué 100 parties au casino. À ce stade, il paie presque le loyer.',
    howToObtain: 'Joue 100 parties au casino.',
    icon: '🏛️',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#1c1917', '#92400e'),
    backgroundColor: '#1c1917',
    borderColor: '#fbbf24',
    iconColor: '#fef3c7',
    rarity: 'epic',
  },
  {
    autoConditionKey: 'CASINO_WIN_1',
    name: 'Ça Passe',
    description: 'A remporté sa première partie au casino.',
    howToObtain: 'Gagne une partie au casino.',
    icon: '🍀',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#166534', '#22c55e'),
    backgroundColor: '#166534',
    borderColor: '#86efac',
    iconColor: '#f0fdf4',
    rarity: 'common',
  },
  {
    autoConditionKey: 'CASINO_WIN_10',
    name: 'Main Chaude',
    description: 'A gagné 10 parties au casino.',
    howToObtain: 'Gagne 10 parties au casino.',
    icon: '🔥',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#166534', '#14532d'),
    backgroundColor: '#166534',
    borderColor: '#4ade80',
    iconColor: '#ecfdf5',
    rarity: 'uncommon',
  },
  {
    autoConditionKey: 'CASINO_WIN_25',
    name: 'Veine Insolente',
    description: 'A gagné 25 parties au casino. La chance abuse un peu.',
    howToObtain: 'Gagne 25 parties au casino.',
    icon: '♠️',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#14532d', '#064e3b'),
    backgroundColor: '#14532d',
    borderColor: '#6ee7b7',
    iconColor: '#f0fdf4',
    rarity: 'rare',
  },
  {
    autoConditionKey: 'CASINO_WIN_50',
    name: 'Croupier Cauchemar',
    description: 'A gagné 50 parties au casino. Le personnel le déteste.',
    howToObtain: 'Gagne 50 parties au casino.',
    icon: '👑',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#14532d', '#065f46'),
    backgroundColor: '#14532d',
    borderColor: '#a7f3d0',
    iconColor: '#f0fdf4',
    rarity: 'epic',
  },
  {
    autoConditionKey: 'CASINO_LOSS_1',
    name: 'Pas de Chance',
    description: 'A perdu sa première partie au casino.',
    howToObtain: 'Perds une partie au casino.',
    icon: '🥲',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#7f1d1d', '#991b1b'),
    backgroundColor: '#7f1d1d',
    borderColor: '#f87171',
    iconColor: '#fff1f2',
    rarity: 'common',
  },
  {
    autoConditionKey: 'CASINO_LOSS_10',
    name: 'Chat Noir',
    description: 'A perdu 10 parties au casino.',
    howToObtain: 'Perds 10 parties au casino.',
    icon: '🐈',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#7f1d1d', '#450a0a'),
    backgroundColor: '#7f1d1d',
    borderColor: '#fca5a5',
    iconColor: '#fff1f2',
    rarity: 'uncommon',
  },
  {
    autoConditionKey: 'CASINO_LOSS_25',
    name: 'Magnétiseur de Défaites',
    description: 'A perdu 25 parties au casino. Une vraie vocation.',
    howToObtain: 'Perds 25 parties au casino.',
    icon: '🫠',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#7f1d1d', '#1f2937'),
    backgroundColor: '#7f1d1d',
    borderColor: '#f87171',
    iconColor: '#fff7ed',
    rarity: 'rare',
  },
  {
    autoConditionKey: 'CASINO_LOSS_50',
    name: 'Abonné aux Pertes',
    description: 'A perdu 50 parties au casino. Une fidélité coûteuse.',
    howToObtain: 'Perds 50 parties au casino.',
    icon: '💀',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#450a0a', '#111827'),
    backgroundColor: '#450a0a',
    borderColor: '#f87171',
    iconColor: '#fee2e2',
    rarity: 'epic',
  },
  {
    autoConditionKey: 'CASINO_JACKPOT_50000',
    name: 'Jackpot 50K',
    description: 'A remporté 50 000$ ou plus en une seule partie au casino.',
    howToObtain: 'Gagne 50 000$ ou plus sur une partie de casino.',
    icon: '💰',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#065f46', '#0f766e'),
    backgroundColor: '#065f46',
    borderColor: '#5eead4',
    iconColor: '#ecfeff',
    rarity: 'rare',
  },
  {
    autoConditionKey: 'CASINO_JACKPOT_100000',
    name: 'Jackpot 100K',
    description: 'A remporté 100 000$ ou plus en une seule partie au casino.',
    howToObtain: 'Gagne 100 000$ ou plus sur une partie de casino.',
    icon: '💎',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#0f172a', '#065f46'),
    backgroundColor: '#0f172a',
    borderColor: '#99f6e4',
    iconColor: '#ecfeff',
    rarity: 'legendary',
  },
  {
    autoConditionKey: 'FLAPPY_BIRD_50',
    name: 'Flappy Pro',
    description: 'A atteint 50 points à Flappy Bird. Ça tient du miracle.',
    howToObtain: 'Atteins un score de 50 à Flappy Bird.',
    icon: '🐦',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#0369a1', '#7dd3fc'),
    backgroundColor: '#0369a1',
    borderColor: '#38bdf8',
    iconColor: '#fef08a',
    rarity: 'rare',
  },
  {
    autoConditionKey: 'MINESWEEPER_WIN',
    name: 'Déminer',
    description: 'A remporté une partie de Démineur sans exploser.',
    howToObtain: 'Gagne une partie de Démineur.',
    icon: '💣',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#374151', '#111827'),
    backgroundColor: '#374151',
    borderColor: '#6b7280',
    iconColor: '#ffffff',
    rarity: 'uncommon',
  },
];

// ─── New achievement badges ───────────────────────────────────────────────────

const NEW_ACHIEVEMENT_BADGES: BadgeDef[] = [
  // Casino big bet badges
  {
    autoConditionKey: 'CASINO_BET_10000',
    name: 'Gros Joueur',
    description: 'A misé 10 000$ ou plus en une seule mise au casino.',
    howToObtain: 'Place une mise d\'au moins 10 000$ au casino.',
    icon: '🎲',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#78350f', '#d97706'),
    backgroundColor: '#78350f',
    borderColor: '#fbbf24',
    iconColor: '#fef3c7',
    rarity: 'uncommon',
  },
  {
    autoConditionKey: 'CASINO_BET_20000',
    name: 'Grand Joueur',
    description: 'A misé 20 000$ ou plus en une seule mise au casino.',
    howToObtain: 'Place une mise d\'au moins 20 000$ au casino.',
    icon: '🃏',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#92400e', '#b45309'),
    backgroundColor: '#92400e',
    borderColor: '#f59e0b',
    iconColor: '#ffffff',
    rarity: 'rare',
  },
  {
    autoConditionKey: 'CASINO_BET_50000',
    name: 'Millionnaire du Casino',
    description: 'A misé 50 000$ ou plus en une seule mise. Les nerfs d\'acier.',
    howToObtain: 'Place une mise d\'au moins 50 000$ au casino.',
    icon: '💎',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#1d4ed8', '#7c3aed'),
    backgroundColor: '#1d4ed8',
    borderColor: '#a78bfa',
    iconColor: '#e0e7ff',
    rarity: 'epic',
  },
  {
    autoConditionKey: 'CASINO_BET_100000',
    name: 'Roi du Casino',
    description: 'A misé 100 000$ ou plus en une seule mise. Légendaire.',
    howToObtain: 'Place une mise d\'au moins 100 000$ au casino.',
    icon: '👑',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#b45309', '#f59e0b'),
    backgroundColor: '#b45309',
    borderColor: '#fde68a',
    iconColor: '#fffbeb',
    rarity: 'legendary',
  },
  // Nuit Blanche
  {
    autoConditionKey: 'NUIT_BLANCHE',
    name: 'Nuit Blanche',
    description: 'Connecté à 3h du matin. Les yeux rougis, le café chaud.',
    howToObtain: 'Connecte-toi entre 3h00 et 4h00 du matin.',
    icon: '🌙',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#0f172a', '#1e1b4b'),
    backgroundColor: '#0f172a',
    borderColor: '#4f46e5',
    iconColor: '#c7d2fe',
    rarity: 'rare',
  },
  // Sudoku difficulty badges
  {
    autoConditionKey: 'SUDOKU_EASY',
    name: 'Sudoku Facile',
    description: 'A complété une grille de sudoku en mode Facile.',
    howToObtain: 'Termine une grille de sudoku en difficulté Facile.',
    icon: '🧩',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#166534', '#22c55e'),
    backgroundColor: '#166534',
    borderColor: '#86efac',
    iconColor: '#f0fdf4',
    rarity: 'common',
  },
  {
    autoConditionKey: 'SUDOKU_MEDIUM',
    name: 'Sudoku Intermédiaire',
    description: 'A complété une grille de sudoku en mode Intermédiaire.',
    howToObtain: 'Termine une grille de sudoku en difficulté Intermédiaire.',
    icon: '🧩',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#0369a1', '#0ea5e9'),
    backgroundColor: '#0369a1',
    borderColor: '#7dd3fc',
    iconColor: '#f0f9ff',
    rarity: 'uncommon',
  },
  {
    autoConditionKey: 'SUDOKU_HARD',
    name: 'Sudoku Difficile',
    description: 'A complété une grille de sudoku en mode Difficile.',
    howToObtain: 'Termine une grille de sudoku en difficulté Difficile.',
    icon: '🧩',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#6d28d9', '#a855f7'),
    backgroundColor: '#6d28d9',
    borderColor: '#d8b4fe',
    iconColor: '#faf5ff',
    rarity: 'rare',
  },
  {
    autoConditionKey: 'SUDOKU_EXPERT',
    name: 'Sudoku Expert',
    description: 'A complété une grille de sudoku en mode Expert. Chapeau.',
    howToObtain: 'Termine une grille de sudoku en difficulté Expert.',
    icon: '🧩',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#991b1b', '#dc2626'),
    backgroundColor: '#991b1b',
    borderColor: '#fca5a5',
    iconColor: '#fff1f2',
    rarity: 'epic',
  },
  // Minesweeper difficulty badges
  {
    autoConditionKey: 'MINESWEEPER_DEBUTANT',
    name: 'Démineur Débutant',
    description: 'A remporté une partie de Démineur en mode Débutant.',
    howToObtain: 'Gagne une partie de Démineur en difficulté Débutant.',
    icon: '💣',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#374151', '#4b5563'),
    backgroundColor: '#374151',
    borderColor: '#9ca3af',
    iconColor: '#f9fafb',
    rarity: 'common',
  },
  {
    autoConditionKey: 'MINESWEEPER_INTERMEDIAIRE',
    name: 'Démineur Intermédiaire',
    description: 'A remporté une partie de Démineur en mode Intermédiaire.',
    howToObtain: 'Gagne une partie de Démineur en difficulté Intermédiaire.',
    icon: '💣',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#065f46', '#059669'),
    backgroundColor: '#065f46',
    borderColor: '#34d399',
    iconColor: '#ecfdf5',
    rarity: 'uncommon',
  },
  {
    autoConditionKey: 'MINESWEEPER_EXPERT',
    name: 'Démineur Expert',
    description: 'A survécu au Démineur en mode Expert. Un héros.',
    howToObtain: 'Gagne une partie de Démineur en difficulté Expert.',
    icon: '💣',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#7c2d12', '#ea580c'),
    backgroundColor: '#7c2d12',
    borderColor: '#fb923c',
    iconColor: '#fff7ed',
    rarity: 'epic',
  },
  // Solitaire win
  {
    autoConditionKey: 'SOLITAIRE_WIN',
    name: 'Solitaire Victorieux',
    description: 'A remporté une partie de Solitaire.',
    howToObtain: 'Gagne une partie de Solitaire.',
    icon: '🃏',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#1e1b4b', '#3730a3'),
    backgroundColor: '#1e1b4b',
    borderColor: '#818cf8',
    iconColor: '#e0e7ff',
    rarity: 'uncommon',
  },
  // Lewis Hamilton (Racer)
  {
    autoConditionKey: 'RACER_LAP',
    name: 'Lewis Hamilton',
    description: 'A complété un tour sur Racer. Vroom.',
    howToObtain: 'Termine un lap sur Racer.',
    icon: '🏎️',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#7f1d1d', '#f97316'),
    backgroundColor: '#7f1d1d',
    borderColor: '#fb923c',
    iconColor: '#fff7ed',
    rarity: 'common',
  },
  // Magnus Carlsen (Chess)
  {
    autoConditionKey: 'CHESS_WIN',
    name: 'Magnus Carlsen',
    description: 'A remporté une partie d\'échecs.',
    howToObtain: 'Gagne une partie d\'échecs.',
    icon: '♟️',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#1c1917', '#44403c'),
    backgroundColor: '#1c1917',
    borderColor: '#a8a29e',
    iconColor: '#fafaf9',
    rarity: 'uncommon',
  },
  // Généreux (Gift)
  {
    autoConditionKey: 'GENEROUS',
    name: 'Généreux',
    description: 'A offert un cadeau à quelqu\'un. La générosité ça se mérite.',
    howToObtain: 'Offre un cadeau à un autre joueur.',
    icon: '🎁',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#be185d', '#ec4899'),
    backgroundColor: '#be185d',
    borderColor: '#f9a8d4',
    iconColor: '#fff0f6',
    rarity: 'uncommon',
  },
  // Bug Reporter
  {
    autoConditionKey: 'BUG_REPORTER',
    name: '☝️🤓',
    description: 'A reporté un bug. Techniquement utile.',
    howToObtain: 'Reporte un bug via le formulaire prévu à cet effet.',
    icon: '🐛',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#166534', '#15803d'),
    backgroundColor: '#166534',
    borderColor: '#4ade80',
    iconColor: '#f0fdf4',
    rarity: 'common',
  },
  // Puissant (Connect 4)
  {
    autoConditionKey: 'PUISSANCE_4_WIN',
    name: 'Puissant',
    description: 'A gagné une partie de Puissance 4.',
    howToObtain: 'Gagne une partie de Puissance 4.',
    icon: '🔴',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#dc2626', '#b91c1c'),
    backgroundColor: '#dc2626',
    borderColor: '#fca5a5',
    iconColor: '#fff1f2',
    rarity: 'common',
  },
  // Ball Arena champion
  {
    autoConditionKey: 'BALL_ARENA_WIN',
    name: 'Boulet de Canon',
    description: 'A expulsé son adversaire de l\'arène.',
    howToObtain: 'Gagne une partie de Ball Arena.',
    icon: '🎱',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#0e7490', '#06b6d4'),
    backgroundColor: '#0e7490',
    borderColor: '#67e8f9',
    iconColor: '#ecfeff',
    rarity: 'common',
  },
  // Première quête quotidienne terminée
  {
    autoConditionKey: 'FIRST_STEP',
    name: 'Premier Pas',
    description: 'A validé sa toute première quête quotidienne.',
    howToObtain: 'Termine une quête quotidienne pour la première fois.',
    icon: '🧭',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#0f766e', '#14b8a6'),
    backgroundColor: '#0f766e',
    borderColor: '#5eead4',
    iconColor: '#f0fdfa',
    rarity: 'common',
  },
  // Quête quotidienne complétée très rapidement
  {
    autoConditionKey: 'SPEEDRUN_DAILY_60S',
    name: 'Speedrunner Quotidien',
    description: 'A complété une quête quotidienne en moins de 60 secondes.',
    howToObtain: 'Termine une quête quotidienne en moins de 60 secondes après sélection.',
    icon: '⚡',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#0c4a6e', '#0284c7'),
    backgroundColor: '#0c4a6e',
    borderColor: '#38bdf8',
    iconColor: '#e0f2fe',
    rarity: 'rare',
  },
  // Gagner entre 2h et 5h du matin
  {
    autoConditionKey: 'NIGHT_OWL_WIN',
    name: 'Hibou Nocturne',
    description: 'A gagné une partie en pleine nuit.',
    howToObtain: 'Gagne une partie entre 2h00 et 4h59.',
    icon: '🦉',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#111827', '#312e81'),
    backgroundColor: '#111827',
    borderColor: '#818cf8',
    iconColor: '#e0e7ff',
    rarity: 'rare',
  },
  // Gagner avant 7h du matin
  {
    autoConditionKey: 'EARLY_BIRD_WIN',
    name: 'Lève-Tôt',
    description: 'A gagné une partie avant 7h du matin.',
    howToObtain: 'Gagne une partie avant 7h00.',
    icon: '🌅',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#b45309', '#f59e0b'),
    backgroundColor: '#b45309',
    borderColor: '#fcd34d',
    iconColor: '#fffbeb',
    rarity: 'uncommon',
  },
  // 10 victoires consécutives
  {
    autoConditionKey: 'PERFECT_10',
    name: 'Perfect 10',
    description: 'A enchaîné 10 victoires d\'affilée tous jeux confondus.',
    howToObtain: 'Obtiens une série de 10 victoires consécutives.',
    icon: '🏅',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#991b1b', '#7c2d12'),
    backgroundColor: '#991b1b',
    borderColor: '#f97316',
    iconColor: '#ffedd5',
    rarity: 'legendary',
  },
  // Plus grand nombre de badges possédés
  {
    autoConditionKey: 'TOP_BADGES_COUNT',
    name: 'Collection Royale',
    description: 'Fait partie des joueurs avec le plus de badges débloqués.',
    howToObtain: 'Avoir le plus grand nombre de badges possédés.',
    icon: '🏆',
    category: 'special',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#78350f', '#f59e0b'),
    backgroundColor: '#78350f',
    borderColor: '#fde68a',
    iconColor: '#fff7ed',
    rarity: 'epic',
  },
  // Posséder au moins 25 badges
  {
    autoConditionKey: 'COLLECTIONNEUR_25',
    name: 'Collectionneur',
    description: 'Possède une collection d\'au moins 25 badges.',
    howToObtain: 'Débloque 25 badges.',
    icon: '🗂️',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#374151', '#1f2937'),
    backgroundColor: '#374151',
    borderColor: '#9ca3af',
    iconColor: '#f3f4f6',
    rarity: 'rare',
  },
  // Offrir au moins 10 cadeaux
  {
    autoConditionKey: 'GENEROUS_10_GIFTS',
    name: 'Mecene',
    description: 'A offert 10 cadeaux ou plus aux autres joueurs.',
    howToObtain: 'Offre 10 cadeaux.',
    icon: '🎁',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#9d174d', '#be185d'),
    backgroundColor: '#9d174d',
    borderColor: '#f9a8d4',
    iconColor: '#fff1f2',
    rarity: 'rare',
  },
  // Gagner 20 paris Polymarket
  {
    autoConditionKey: 'POLYMARKET_20_WINS',
    name: 'Oracle Polymarket',
    description: 'A remporté 20 paris ou plus sur Polymarket.',
    howToObtain: 'Gagne 20 paris sur Polymarket.',
    icon: '📈',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#064e3b', '#059669'),
    backgroundColor: '#064e3b',
    borderColor: '#6ee7b7',
    iconColor: '#ecfdf5',
    rarity: 'epic',
  },
  // Envoyer 50 messages de chat
  {
    autoConditionKey: 'SOCIAL_50_MESSAGES',
    name: 'Voix du Chat',
    description: 'A envoyé au moins 50 messages sur le chat.',
    howToObtain: 'Envoie 50 messages sur le chat global.',
    icon: '💬',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#0f766e', '#0ea5e9'),
    backgroundColor: '#0f766e',
    borderColor: '#67e8f9',
    iconColor: '#ecfeff',
    rarity: 'uncommon',
  },
  // Série quotidienne de 7 jours
  {
    autoConditionKey: 'STREAK_7',
    name: 'Serie 7 Jours',
    description: 'A maintenu une série quotidienne de 7 jours.',
    howToObtain: 'Atteins une série de 7 jours au Daily Pass.',
    icon: '📅',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#1e3a8a', '#2563eb'),
    backgroundColor: '#1e3a8a',
    borderColor: '#93c5fd',
    iconColor: '#eff6ff',
    rarity: 'uncommon',
  },
  // Série quotidienne de 30 jours
  {
    autoConditionKey: 'STREAK_30',
    name: 'Serie 30 Jours',
    description: 'A maintenu une série quotidienne de 30 jours.',
    howToObtain: 'Atteins une série de 30 jours au Daily Pass.',
    icon: '🗓️',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#4c1d95', '#7c3aed'),
    backgroundColor: '#4c1d95',
    borderColor: '#c4b5fd',
    iconColor: '#f5f3ff',
    rarity: 'epic',
  },
  // 3 filleuls approuvés
  {
    autoConditionKey: 'MENTOR_3_REFERRALS',
    name: 'Mentor',
    description: 'A parrainé 3 joueurs approuvés ou plus.',
    howToObtain: 'Fais approuver 3 filleuls via ton code de parrainage.',
    icon: '🤝',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#92400e', '#ea580c'),
    backgroundColor: '#92400e',
    borderColor: '#fdba74',
    iconColor: '#fff7ed',
    rarity: 'rare',
  },
  // Participer a 10 guerres de clan terminees
  {
    autoConditionKey: 'CLAN_WARS_10',
    name: 'Veteran des Guerres',
    description: 'A participe a 10 guerres de clan terminees ou plus.',
    howToObtain: 'Participe a 10 guerres de clan completees.',
    icon: '⚔️',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#7f1d1d', '#b91c1c'),
    backgroundColor: '#7f1d1d',
    borderColor: '#fca5a5',
    iconColor: '#fff1f2',
    rarity: 'epic',
  },
  // MVP de clan sur 3 guerres terminees
  {
    autoConditionKey: 'CLAN_MVP_3',
    name: 'MVP de Guerre',
    description: 'A ete meilleur attaquant de son clan sur 3 guerres terminees.',
    howToObtain: 'Deviens MVP de ton clan sur 3 guerres completees.',
    icon: '🥇',
    category: 'achievement',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#713f12', '#ca8a04'),
    backgroundColor: '#713f12',
    borderColor: '#fde047',
    iconColor: '#fefce8',
    rarity: 'legendary',
  },
  // Completer une categorie entiere de badges actifs
  {
    autoConditionKey: 'MYTHIC_CATEGORY_COMPLETE',
    name: 'Collection Mythique',
    description: 'Possede tous les badges actifs d\'au moins une categorie.',
    howToObtain: 'Complete entierement une categorie de badges actifs.',
    icon: '🌌',
    category: 'special',
    backgroundType: 'gradient',
    backgroundGradient: GRAD('#312e81', '#7c3aed'),
    backgroundColor: '#312e81',
    borderColor: '#c4b5fd',
    iconColor: '#f5f3ff',
    rarity: 'legendary',
  },
];

const ALL_DEFAULT_BADGES: BadgeDef[] = [
  MEMBER_BADGE,
  ...CLASS_BADGES,
  ...AURA_BADGES,
  ...MONEY_BADGES,
  ...GAME_BADGES,
  BOMBPARTY_BADGE,
  ...ACHIEVEMENT_BADGES,
  ...NEW_ACHIEVEMENT_BADGES,
];

// ─── Idempotent seeder ────────────────────────────────────────────────────────

/**
 * Creates all default automatic badges if they don't already exist.
 * Safe to call on every server startup.
 */
export const ensureDefaultBadges = async (): Promise<void> => {
  try {
    for (const def of ALL_DEFAULT_BADGES) {
      const existing = await prisma.badge.findFirst({
        where: { autoConditionKey: def.autoConditionKey },
        select: { id: true },
      });
      if (!existing) {
        await prisma.badge.create({
          data: {
            name: def.name,
            description: def.description,
            howToObtain: def.howToObtain,
            icon: def.icon,
            backgroundType: def.backgroundType,
            backgroundColor: def.backgroundColor,
            backgroundGradient: def.backgroundGradient ?? null,
            backgroundImage: null,
            iconColor: def.iconColor,
            borderColor: def.borderColor,
            category: def.category,
            rarity: def.rarity,
            isAutomatic: true,
            autoConditionKey: def.autoConditionKey,
            isActive: true,
            isHidden: def.isHidden ?? false,
          },
        });
      }
    }
    console.log(`[badges] Default badges seeded (${ALL_DEFAULT_BADGES.length} definitions checked)`);
  } catch (error) {
    console.error('[badges] Failed to seed default badges:', error);
  }
};
