ALTER TABLE "User" ADD COLUMN "dailyGameAuraGiven" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "dailyGameMoneyGiven" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "dailyGameAuraLimit" INTEGER NOT NULL DEFAULT 500;
ALTER TABLE "User" ADD COLUMN "dailyGameMoneyLimit" INTEGER NOT NULL DEFAULT 1000;
ALTER TABLE "User" ADD COLUMN "lastDailyGameReset" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
