import { Briefcase, Coins, Gamepad2, Gavel, Lightbulb, LogIn, MessageCircle, Newspaper, Shield, Store, TrendingUp, Users } from 'lucide-react';

export type LogTypeConfigEntry = {
  label: string;
  color: string;
  bgColor: string;
  borderColor: string;
  icon: React.ComponentType<{ className?: string }>;
};

export const LOG_TYPE_CONFIG: Record<string, LogTypeConfigEntry> = {
  AUTH: { label: 'Connexion', color: 'text-blue-400', bgColor: 'bg-blue-500', borderColor: 'border-blue-500', icon: LogIn },
  CHAT: { label: 'Chat', color: 'text-green-400', bgColor: 'bg-green-500', borderColor: 'border-green-500', icon: MessageCircle },
  GAME: { label: 'Jeux', color: 'text-purple-400', bgColor: 'bg-purple-500', borderColor: 'border-purple-500', icon: Gamepad2 },
  ECONOMY: { label: 'Economie', color: 'text-yellow-400', bgColor: 'bg-yellow-500', borderColor: 'border-yellow-500', icon: Coins },
  PARTY: { label: 'Groupe', color: 'text-pink-400', bgColor: 'bg-pink-500', borderColor: 'border-pink-500', icon: Users },
  MARKETPLACE: { label: 'Boutique', color: 'text-orange-400', bgColor: 'bg-orange-500', borderColor: 'border-orange-500', icon: Store },
  ADMIN: { label: 'Admin', color: 'text-red-400', bgColor: 'bg-red-500', borderColor: 'border-red-500', icon: Shield },
  BAN: { label: 'Bans', color: 'text-red-300', bgColor: 'bg-red-700', borderColor: 'border-red-700', icon: Gavel },
  SUGGESTION: { label: 'Suggestions', color: 'text-cyan-400', bgColor: 'bg-cyan-500', borderColor: 'border-cyan-500', icon: Lightbulb },
  AURACOIN: { label: 'AuraCoin', color: 'text-amber-400', bgColor: 'bg-amber-500', borderColor: 'border-amber-500', icon: TrendingUp },
  BUSINESS: { label: 'Business', color: 'text-emerald-400', bgColor: 'bg-emerald-600', borderColor: 'border-emerald-600', icon: Briefcase },
  FORUM: { label: 'Forum', color: 'text-indigo-400', bgColor: 'bg-indigo-500', borderColor: 'border-indigo-500', icon: Newspaper },
};

export const ACTION_LABELS: Record<string, string> = {
  login: 'Connexion',
  logout: 'Déconnexion',
  register: 'Inscription',
  login_failed: 'Connexion échouée',
  login_banned: 'Connexion bannie',
  message_sent: 'Message envoyé',
  message_deleted: 'Message supprimé',
  game_complete: 'Partie terminée',
  game_reward: 'Récompense obtenue',
  casino_bet: 'Pari casino',
  highscore: 'Nouveau record',
  reward_fallback: 'Récompense de secours',
  transfer: 'Transfert',
  balance_change: 'Modification solde',
  pass_reward: 'Récompense pass',
  party_create: 'Groupe créé',
  party_join: 'Rejoint groupe',
  party_leave: 'Quitté groupe',
  party_disband: 'Groupe dissous',
  party_kick: 'Expulsion',
  party_invite: 'Invitation envoyée',
  suggestion_create: 'Suggestion créée',
  suggestion_vote: 'Vote',
  suggestion_comment: 'Commentaire',
  suggestion_delete: 'Suggestion supprimée',
  bug_report: 'Bug signalé',
  item_purchase: 'Achat',
  item_use: 'Utilisation objet',
  item_create: 'Objet créé',
  item_import: 'Objets importés',
  item_delete: 'Objet supprimé',
  user_update: 'Utilisateur modifié',
  user_delete: 'Utilisateur supprimé',
  user_approve: 'Utilisateur approuvé',
  user_reject: 'Utilisateur refusé',
  inventory_add: 'Inventaire ajouté',
  inventory_update: 'Inventaire modifié',
  inventory_remove: 'Inventaire retiré',
  chat_clear: 'Chat vidé',
  chat_export: 'Chat exporté',
  stats_delete: 'Stats supprimées',
  business_create: 'Entreprise créée',
  business_delete: 'Entreprise supprimée',
  business_invite: 'Invitation business envoyée',
  business_loan_request: 'Demande de prêt business',
  business_loan_decision: 'Décision prêt business',
  business_loan_repay: 'Prêt business remboursé',
  business_deposit: 'Dépôt business',
  business_withdraw: 'Retrait business',
  business_invest: 'Investissement business',
  business_transfer: 'Transfert business',
  business_transfer_fee_update: 'Frais de transfert modifiés',
  business_buyout_offer_create: 'Offre de rachat créée',
  business_buyout_offer_respond: 'Offre de rachat traitée',
  business_buyout_offer_cancel: 'Offre de rachat annulée',
  business_research_start: 'Recherche business lancée',
  business_share_proposal_cancel: 'Proposition actionnaire annulée',
  business_product_deploy: 'Produit startup déployé',
  business_collect: 'Recette business collectée',
  business_sale: 'Vente business enregistrée',
  business_profile_update: 'Profil business modifié',
  business_invitation_respond: 'Invitation business traitée',
  business_member_sack: 'Membre business renvoyé',
  business_member_salary_update: 'Salaire business modifié',
  business_formation_product_buy: 'Produit formation acheté',
  business_rate: 'Business noté',
  bank_upgrade_purchase: 'Upgrade bancaire acheté',
  bank_rate_update: 'Taux bancaire modifié',
  bank_account_open: 'Compte bancaire ouvert',
  bank_account_deposit: 'Dépôt bancaire',
  bank_account_withdraw: 'Retrait bancaire',
  formation_update: 'Formation modifiée',
  formation_purchase: 'Formation achetée',
  formation_product_create: 'Produit formation créé',
  formation_product_update: 'Produit formation modifié',
  formation_product_delete: 'Produit formation supprimé',
  relationship_create: 'Relation créée',
  relationship_forget: 'Relation supprimée',
  relationship_reactivate: 'Relation relancée',
  marriage_proposal: 'Demande en mariage',
  marriage_response: 'Réponse mariage',
  divorce_proposal: 'Demande de divorce',
  divorce_response: 'Réponse divorce',
  relationship_force_divorce: 'Divorce forcé',
  relationship_mistress: 'Liaison créée',
  relationship_cheating_report: 'Soupçon de tricherie',
  relationship_court_case: 'Décision tribunal',
  couple_deposit: 'Dépôt compte commun',
  couple_withdraw: 'Retrait compte commun',
  update_popup_create: 'Popup changelog créée',
  update_popup_update: 'Popup changelog modifiée',
  update_popup_delete: 'Popup changelog supprimée',
  clan_update: 'Clan modifié',
  clan_transfer_leadership: 'Chef de clan modifié',
  clan_delete: 'Clan supprimé',
  horses_reset: 'Chevaux et ecuries reinitialises',
  ban_create: 'Bannissement créé',
  ban_remove: 'Bannissement levé',
  auracoin_buy: 'Achat AuraCoin',
  auracoin_sell: 'Vente AuraCoin',
  // Economy
  gift_aura: 'Don d\'aura',
  quest_reward: 'Récompense quête',
  // Game
  casino_start: 'Casino démarré',
  // Party
  party_update: 'Groupe modifié',
  // Suggestion
  suggestion_status: 'Statut suggestion modifié',
  suggestion_rating: 'Suggestion notée',
  // Marketplace
  listing_create: 'Listing créé',
  listing_sold: 'Listing vendu',
  listing_cancel: 'Listing annulé',
  // Admin – users
  registration_reviews_import: 'Inscriptions importées',
  item_update: 'Objet modifié',
  item_image_upload: 'Image objet téléchargée',
  shop_categories_update: 'Catégories boutique modifiées',
  badge_create: 'Badge créé',
  badge_assign: 'Badge attribué',
  badge_remove: 'Badge retiré',
  badge_equip: 'Badge équipé',
  setting_update: 'Paramètre modifié',
  settings_bulk_update: 'Paramètres modifiés en masse',
  tax_brackets_update: 'Tranches fiscales modifiées',
  tax_manual_run: 'Taxe déclenchée manuellement',
  daily_tax_run: 'Taxe journalière exécutée',
  extreme_aura_reset: 'Aura extrême réinitialisée',
  deploy_trigger: 'Déploiement déclenché',
  polymarket_event_create: 'Événement Polymarket créé',
  polymarket_event_update: 'Événement Polymarket modifié',
  polymarket_event_resolve: 'Événement Polymarket résolu',
  polymarket_event_delete: 'Événement Polymarket supprimé',
  polymarket_suggestion_approve: 'Suggestion Polymarket approuvée',
  polymarket_suggestion_reject: 'Suggestion Polymarket refusée',
  gift_template_create: 'Modèle cadeau créé',
  gift_template_update: 'Modèle cadeau modifié',
  gift_template_delete: 'Modèle cadeau supprimé',
  bombparty_prompts_recalculate: 'Prompts BombParty recalculés',
  bug_report_update: 'Bug report modifié',
  bug_report_delete: 'Bug report supprimé',
  online_snapshot_create: 'Snapshot en ligne créé',
  appeal_reject: 'Appel refusé',
  username_change: 'Pseudo changé',
  username_change_reject: 'Changement de pseudo refusé',
  user_follow: 'Suivi utilisateur',
  user_unfollow: 'Désabonnement utilisateur',
  name_change_request: 'Demande de changement de pseudo',
  // Admin – clans
  clan_create: 'Clan créé',
  clan_join: 'Rejoint clan',
  clan_leave: 'Quitté clan',
  clan_kick: 'Expulsé du clan',
  clan_promote: 'Membre promu',
  clan_demote: 'Membre rétrogradé',
  clan_war_declare: 'Guerre de clan déclarée',
  clan_war_attack: 'Attaque de guerre de clan',
  clan_war_fortify: 'Fortification guerre de clan',
  clan_war_game: 'Jeu de guerre de clan',
  clan_bank_deposit: 'Dépôt banque de clan',
  // Admin – modération
  warning_create: 'Avertissement créé',
  warning_delete: 'Avertissement supprimé',
  skill_train: 'Compétence entraînée',
  business_share_proposal_create: 'Proposition actionnaire créée',
  business_share_proposal_review: 'Proposition actionnaire évaluée',
  bank_daily_revenue: 'Revenu bancaire journalier',
  formation_product_review: 'Produit formation évalué',
  ad_approve: 'Publicité approuvée',
  ad_reject: 'Publicité refusée',
  ad_delete_forever: 'Publicité supprimée définitivement',
  // Forum
  subreddit_create: 'Subreddit créé',
  subreddit_join: 'Rejoint subreddit',
  subreddit_leave: 'Quitté subreddit',
  forum_post_create: 'Post créé',
  forum_post_delete: 'Post supprimé',
  forum_comment_create: 'Commentaire créé',
  forum_comment_delete: 'Commentaire supprimé',
};
