const GAME_IMAGE_BY_ID: Record<string, string> = {
  'russian-roulette': '/images/game-covers/russian-roulette.webp',
  'bomb-party': '/images/game-covers/bomb-party.webp',
  poker: '/images/game-covers/poker.webp',
  'petit-bac': '/images/game-covers/petit-bac.webp',
  uno: '/images/game-covers/uno.webp',
  loto: '/images/game-covers/loto.webp',
  'bataille-navale': '/images/game-covers/bataille-navale.webp',
  'doodle-jump': '/images/game-covers/doodle-jump.webp',
  blockblast: '/images/game-covers/blockblast.webp',
  'logic-lab': '/images/game-covers/logic-lab.webp',
  minesweeper: '/images/game-covers/minesweeper.webp',
  hextris: '/images/game-covers/hextris.webp',
  'paper-io': '/images/game-covers/paper-io.webp',
  'game-2048': '/images/game-covers/game-2048.webp',
  'flappy-bird': '/images/game-covers/flappy-bird.webp',
  'chrome-dino': '/images/game-covers/chrome-dino.webp',
  snake: '/images/game-covers/snake.webp',
  'stack-tower': '/images/game-covers/stack-tower.webp',
  'fruit-ninja': '/images/game-covers/fruit-ninja.webp',
  'qs-watermelon': '/images/game-covers/qs-watermelon.webp',
  'geometry-dash': '/images/game-covers/geometry-dash.webp',
  casino: '/images/game-covers/casino.webp',
  'market-room': '/images/game-covers/market-room.webp',
  solitaire: '/images/game-covers/solitaire.webp',
  racer: '/images/game-covers/racer.webp',
  tetris: '/images/game-covers/tetris.webp',
  'knife-hit': '/images/game-covers/knife-hit.webp',
  'clash-village': '/images/game-covers/clash-village.webp',
  'goyave-empire': '/images/game-covers/goyave-empire.webp',
  polytrack: '/images/game-covers/polytrack.webp',
  eaglercraft: '/images/game-covers/eaglercraft.webp',
  hexgl: '/images/game-covers/hexgl.webp',
  'crossy-road': '/images/game-covers/crossy-road.webp',
  'puissance-quatre': '/images/game-covers/puissance-quatre.webp',
  echecs: '/images/game-covers/echecs.webp',
  'ball-arena': '/images/game-covers/ball-arena.webp',
  morpion: '/images/game-covers/morpion.webp',
  dotsandboxes: '/images/game-covers/dotsandboxes.webp',
  'horse-race': '/images/game-covers/horse-race.webp',
};

export const getGameImage = (gameId: string) => {
  return GAME_IMAGE_BY_ID[gameId] ?? '';
};
